/* hello world! */
var $jscomp={scope:{},getGlobal:function(n){return"undefined"!=typeof window&&window===n?n:"undefined"!=typeof global?global:n}};$jscomp.global=$jscomp.getGlobal(this);$jscomp.initSymbol=function(){$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol);$jscomp.initSymbol=function(){}};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(n){return"jscomp_symbol_"+n+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();$jscomp.global.Symbol.iterator||($jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));$jscomp.initSymbolIterator=function(){}};
$jscomp.makeIterator=function(n){$jscomp.initSymbolIterator();if(n[$jscomp.global.Symbol.iterator])return n[$jscomp.global.Symbol.iterator]();if(!(n instanceof Array||"string"==typeof n||n instanceof String))throw new TypeError(n+" is not iterable");var y=0;return{next:function(){return y==n.length?{done:!0}:{done:!1,value:n[y++]}}}};$jscomp.arrayFromIterator=function(n){for(var y,K=[];!(y=n.next()).done;)K.push(y.value);return K};
$jscomp.arrayFromIterable=function(n){return n instanceof Array?n:$jscomp.arrayFromIterator($jscomp.makeIterator(n))};$jscomp.arrayFromArguments=function(n){for(var y=[],K=0;K<n.length;K++)y.push(n[K]);return y};
$jscomp.inherits=function(n,y){function K(){}K.prototype=y.prototype;n.prototype=new K;n.prototype.constructor=n;for(var B in y)if($jscomp.global.Object.defineProperties){var O=$jscomp.global.Object.getOwnPropertyDescriptor(y,B);void 0!==O&&$jscomp.global.Object.defineProperty(n,B,O)}else n[B]=y[B]};
!function(n,y){"object"==typeof module&&"object"==typeof module.exports?module.exports=n.document?y(n,!0):function(n){if(!n.document)throw Error("jQuery requires a window with a document");return y(n)}:y(n)}("undefined"!=typeof window?window:this,function(n,y){function K(a){var b=!!a&&"length"in a&&a.length,c=d.type(a);return"function"===c||d.isWindow(a)?!1:"array"===c||0===b||"number"==typeof b&&0<b&&b-1 in a}function B(a,b,c){if(d.isFunction(b))return d.grep(a,function(a,d){return!!b.call(a,d,a)!==
c});if(b.nodeType)return d.grep(a,function(a){return a===b!==c});if("string"==typeof b){if(Ob.test(b))return d.filter(b,a,c);b=d.filter(b,a)}return d.grep(a,function(a){return-1<ua.call(b,a)!==c})}function O(a,b){for(;(a=a[b])&&1!==a.nodeType;);return a}function qa(a){var b={};return d.each(a.match(P)||[],function(a,d){b[d]=!0}),b}function ha(){q.removeEventListener("DOMContentLoaded",ha);n.removeEventListener("load",ha);d.ready()}function Y(){this.expando=d.expando+Y.uid++}function M(a,b,c){var e;
if(void 0===c&&1===a.nodeType)if(e="data-"+b.replace(Xa,"-$&").toLowerCase(),c=a.getAttribute(e),"string"==typeof c){try{c="true"===c?!0:"false"===c?!1:"null"===c?null:+c+""===c?+c:Pb.test(c)?d.parseJSON(c):c}catch(f){}D.set(a,b,c)}else c=void 0;return c}function Ya(a,b,c,e){var f,g=1,h=20,k=e?function(){return e.cur()}:function(){return d.css(a,b,"")},l=k(),r=c&&c[3]||(d.cssNumber[b]?"":"px"),p=(d.cssNumber[b]||"px"!==r&&+l)&&ia.exec(d.css(a,b));if(p&&p[3]!==r){r=r||p[3];c=c||[];p=+l||1;do g=g||
".5",p/=g,d.style(a,b,p+r);while(g!==(g=k()/l)&&1!==g&&--h)}return c&&(p=+p||+l||0,f=c[1]?p+(c[1]+1)*c[2]:+c[2],e&&(e.unit=r,e.start=p,e.end=f)),f}function J(a,b){var c="undefined"!=typeof a.getElementsByTagName?a.getElementsByTagName(b||"*"):"undefined"!=typeof a.querySelectorAll?a.querySelectorAll(b||"*"):[];return void 0===b||b&&d.nodeName(a,b)?d.merge([a],c):c}function Ha(a,b){for(var c=0,d=a.length;d>c;c++)v.set(a[c],"globalEval",!b||v.get(b[c],"globalEval"))}function Za(a,b,c,e,f){for(var g,
h,k,l,r=b.createDocumentFragment(),p=[],m=0,n=a.length;n>m;m++)if(g=a[m],g||0===g)if("object"===d.type(g))d.merge(p,g.nodeType?[g]:g);else if(Qb.test(g)){h=h||r.appendChild(b.createElement("div"));k=($a.exec(g)||["",""])[1].toLowerCase();k=Q[k]||Q._default;h.innerHTML=k[1]+d.htmlPrefilter(g)+k[2];for(k=k[0];k--;)h=h.lastChild;d.merge(p,h.childNodes);h=r.firstChild;h.textContent=""}else p.push(b.createTextNode(g));r.textContent="";for(m=0;g=p[m++];)if(e&&-1<d.inArray(g,e))f&&f.push(g);else if(l=d.contains(g.ownerDocument,
g),h=J(r.appendChild(g),"script"),l&&Ha(h),c)for(k=0;g=h[k++];)ab.test(g.type||"")&&c.push(g);return r}function za(){return!0}function U(){return!1}function bb(){try{return q.activeElement}catch(a){}}function Ia(a,b,c,e,f,g){var h,k;if("object"==typeof b){"string"!=typeof c&&(e=e||c,c=void 0);for(k in b)Ia(a,k,c,e,b[k],g);return a}if(null==e&&null==f?(f=c,e=c=void 0):null==f&&("string"==typeof c?(f=e,e=void 0):(f=e,e=c,c=void 0)),!1===f)f=U;else if(!f)return a;return 1===g&&(h=f,f=function(a){return d().off(a),
h.apply(this,arguments)},f.guid=h.guid||(h.guid=d.guid++)),a.each(function(){d.event.add(this,b,f,e,c)})}function cb(a,b){return d.nodeName(a,"table")&&d.nodeName(11!==b.nodeType?b:b.firstChild,"tr")?a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function Rb(a){return a.type=(null!==a.getAttribute("type"))+"/"+a.type,a}function Sb(a){var b=Tb.exec(a.type);return b?a.type=b[1]:a.removeAttribute("type"),a}function db(a,b){var c,e,f,g,h,k;if(1===b.nodeType){if(v.hasData(a)&&
(c=v.access(a),e=v.set(b,c),k=c.events))for(f in delete e.handle,e.events={},k)for(c=0,e=k[f].length;e>c;c++)d.event.add(b,f,k[f][c]);D.hasData(a)&&(g=D.access(a),h=d.extend({},g),D.set(b,h))}}function ca(a,b,c,e){b=eb.apply([],b);var f,g,h,k,l=0,r=a.length,p=r-1,m=b[0],n=d.isFunction(m);if(n||1<r&&"string"==typeof m&&!w.checkClone&&Ub.test(m))return a.each(function(d){var f=a.eq(d);n&&(b[0]=m.call(this,d,f.html()));ca(f,b,c,e)});if(r&&(f=Za(b,a[0].ownerDocument,!1,a,e),g=f.firstChild,1===f.childNodes.length&&
(f=g),g||e)){g=d.map(J(f,"script"),Rb);for(h=g.length;r>l;l++)k=f,l!==p&&(k=d.clone(k,!0,!0),h&&d.merge(g,J(k,"script"))),c.call(a[l],k,l);if(h)for(f=g[g.length-1].ownerDocument,d.map(g,Sb),l=0;h>l;l++)k=g[l],ab.test(k.type||"")&&!v.access(k,"globalEval")&&d.contains(f,k)&&(k.src?d._evalUrl&&d._evalUrl(k.src):d.globalEval(k.textContent.replace(Vb,"")))}return a}function gb(a,b,c){for(var e=b?d.filter(b,a):a,f=0;null!=(b=e[f]);f++)c||1!==b.nodeType||d.cleanData(J(b)),b.parentNode&&(c&&d.contains(b.ownerDocument,
b)&&Ha(J(b,"script")),b.parentNode.removeChild(b));return a}function hb(a,b){var c=d(b.createElement(a)).appendTo(b.body),e=d.css(c[0],"display");return c.detach(),e}function Ja(a){var b=q,c=ib[a];return c||(c=hb(a,b),"none"!==c&&c||(Aa=(Aa||d("<iframe frameborder='0' width='0' height='0'/>")).appendTo(b.documentElement),b=Aa[0].contentDocument,b.write(),b.close(),c=hb(a,b),Aa.detach()),ib[a]=c),c}function ja(a,b,c){var e,f,g,h,k=a.style;return c=c||Ba(a),h=c?c.getPropertyValue(b)||c[b]:void 0,""!==
h&&void 0!==h||d.contains(a.ownerDocument,a)||(h=d.style(a,b)),c&&!w.pixelMarginRight()&&Ka.test(h)&&jb.test(b)&&(e=k.width,f=k.minWidth,g=k.maxWidth,k.minWidth=k.maxWidth=k.width=h,h=c.width,k.width=e,k.minWidth=f,k.maxWidth=g),void 0!==h?h+"":h}function La(a,b){return{get:function(){return a()?void delete this.get:(this.get=b).apply(this,arguments)}}}function kb(a){if(a in lb)return a;for(var b=a[0].toUpperCase()+a.slice(1),c=mb.length;c--;)if(a=mb[c]+b,a in lb)return a}function nb(a,b,c){return(a=
ia.exec(b))?Math.max(0,a[2]-(c||0))+(a[3]||"px"):b}function ob(a,b,c,e,f){b=c===(e?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===c&&(g+=d.css(a,c+da[b],!0,f)),e?("content"===c&&(g-=d.css(a,"padding"+da[b],!0,f)),"margin"!==c&&(g-=d.css(a,"border"+da[b]+"Width",!0,f))):(g+=d.css(a,"padding"+da[b],!0,f),"padding"!==c&&(g+=d.css(a,"border"+da[b]+"Width",!0,f)));return g}function pb(a,b,c){var e=!0,f="width"===b?a.offsetWidth:a.offsetHeight,g=Ba(a),h="border-box"===d.css(a,"boxSizing",
!1,g);if(q.msFullscreenElement&&n.top!==n&&a.getClientRects().length&&(f=Math.round(100*a.getBoundingClientRect()[b])),0>=f||null==f){if(f=ja(a,b,g),(0>f||null==f)&&(f=a.style[b]),Ka.test(f))return f;e=h&&(w.boxSizingReliable()||f===a.style[b]);f=parseFloat(f)||0}return f+ob(a,b,c||(h?"border":"content"),e,g)+"px"}function qb(a,b){for(var c,e,f,g=[],h=0,k=a.length;k>h;h++)e=a[h],e.style&&(g[h]=v.get(e,"olddisplay"),c=e.style.display,b?(g[h]||"none"!==c||(e.style.display=""),""===e.style.display&&
Z(e)&&(g[h]=v.access(e,"olddisplay",Ja(e.nodeName)))):(f=Z(e),"none"===c&&f||v.set(e,"olddisplay",f?c:d.css(e,"display"))));for(h=0;k>h;h++)e=a[h],e.style&&(b&&"none"!==e.style.display&&""!==e.style.display||(e.style.display=b?g[h]||"":"none"));return a}function C(a,b,c,d,f){return new C.prototype.init(a,b,c,d,f)}function rb(){return n.setTimeout(function(){ka=void 0}),ka=d.now()}function Ca(a,b){var c,d=0,f={height:a};for(b=b?1:0;4>d;d+=2-b)c=da[d],f["margin"+c]=f["padding"+c]=a;return b&&(f.opacity=
f.width=a),f}function sb(a,b,c){for(var d,f=(R.tweeners[b]||[]).concat(R.tweeners["*"]),g=0,h=f.length;h>g;g++)if(d=f[g].call(c,b,a))return d}function Wb(a,b){var c,e,f,g,h;for(c in a)if(e=d.camelCase(c),f=b[e],g=a[c],d.isArray(g)&&(f=g[1],g=a[c]=g[0]),c!==e&&(a[e]=g,delete a[c]),h=d.cssHooks[e],h&&"expand"in h)for(c in g=h.expand(g),delete a[e],g)c in a||(a[c]=g[c],b[c]=f);else b[e]=f}function R(a,b,c){var e,f=0,g=R.prefilters.length,h=d.Deferred().always(function(){delete k.elem}),k=function(){if(e)return!1;
for(var b=ka||rb(),b=Math.max(0,l.startTime+l.duration-b),c=1-(b/l.duration||0),d=0,f=l.tweens.length;f>d;d++)l.tweens[d].run(c);return h.notifyWith(a,[l,c,b]),1>c&&f?b:(h.resolveWith(a,[l]),!1)},l=h.promise({elem:a,props:d.extend({},b),opts:d.extend(!0,{specialEasing:{},easing:d.easing._default},c),originalProperties:b,originalOptions:c,startTime:ka||rb(),duration:c.duration,tweens:[],createTween:function(b,c){var e=d.Tween(a,l.opts,b,c,l.opts.specialEasing[b]||l.opts.easing);return l.tweens.push(e),
e},stop:function(b){var c=0,d=b?l.tweens.length:0;if(e)return this;for(e=!0;d>c;c++)l.tweens[c].run(1);return b?(h.notifyWith(a,[l,1,0]),h.resolveWith(a,[l,b])):h.rejectWith(a,[l,b]),this}});c=l.props;for(Wb(c,l.opts.specialEasing);g>f;f++)if(b=R.prefilters[f].call(l,a,c,l.opts))return d.isFunction(b.stop)&&(d._queueHooks(l.elem,l.opts.queue).stop=d.proxy(b.stop,b)),b;return d.map(c,sb,l),d.isFunction(l.opts.start)&&l.opts.start.call(a,l),d.fx.timer(d.extend(k,{elem:a,anim:l,queue:l.opts.queue})),
l.progress(l.opts.progress).done(l.opts.done,l.opts.complete).fail(l.opts.fail).always(l.opts.always)}function aa(a){return a.getAttribute&&a.getAttribute("class")||""}function tb(a){return function(b,c){"string"!=typeof b&&(c=b,b="*");var e,f=0,g=b.toLowerCase().match(P)||[];if(d.isFunction(c))for(;e=g[f++];)"+"===e[0]?(e=e.slice(1)||"*",(a[e]=a[e]||[]).unshift(c)):(a[e]=a[e]||[]).push(c)}}function ub(a,b,c,e){function f(k){var l;return g[k]=!0,d.each(a[k]||[],function(a,d){var k=d(b,c,e);return"string"!=
typeof k||h||g[k]?h?!(l=k):void 0:(b.dataTypes.unshift(k),f(k),!1)}),l}var g={},h=a===Ma;return f(b.dataTypes[0])||!g["*"]&&f("*")}function Na(a,b){var c,e,f=d.ajaxSettings.flatOptions||{};for(c in b)void 0!==b[c]&&((f[c]?a:e||(e={}))[c]=b[c]);return e&&d.extend(!0,a,e),a}function Oa(a,b,c,e){var f;if(d.isArray(b))d.each(b,function(b,d){c||Xb.test(a)?e(a,d):Oa(a+"["+("object"==typeof d&&null!=d?b:"")+"]",d,c,e)});else if(c||"object"!==d.type(b))e(a,b);else for(f in b)Oa(a+"["+f+"]",b[f],c,e)}function vb(a){return d.isWindow(a)?
a:9===a.nodeType&&a.defaultView}var N=[],q=n.document,F=N.slice,eb=N.concat,Pa=N.push,ua=N.indexOf,Da={},Yb=Da.toString,Qa=Da.hasOwnProperty,w={},d=function(a,b){return new d.fn.init(a,b)},Zb=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,$b=/^-ms-/,ac=/-([\da-z])/gi,bc=function(a,b){return b.toUpperCase()};$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();d.fn=d.prototype={jquery:"2.2.1",constructor:d,selector:"",length:0,toArray:function(){return F.call(this)},
get:function(a){return null!=a?0>a?this[a+this.length]:this[a]:F.call(this)},pushStack:function(a){a=d.merge(this.constructor(),a);return a.prevObject=this,a.context=this.context,a},each:function(a){return d.each(this,a)},map:function(a){return this.pushStack(d.map(this,function(b,c){return a.call(b,c,b)}))},slice:function(){return this.pushStack(F.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=
a&&b>a?[this[a]]:[])},end:function(){return this.prevObject||this.constructor()},push:Pa,sort:N.sort,splice:N.splice};d.extend=d.fn.extend=function(){var a,b,c,e,f,g,h=arguments[0]||{},k=1,l=arguments.length,r=!1;"boolean"==typeof h&&(r=h,h=arguments[k]||{},k++);"object"==typeof h||d.isFunction(h)||(h={});for(k===l&&(h=this,k--);l>k;k++)if(null!=(a=arguments[k]))for(b in a)c=h[b],e=a[b],h!==e&&(r&&e&&(d.isPlainObject(e)||(f=d.isArray(e)))?(f?(f=!1,g=c&&d.isArray(c)?c:[]):g=c&&d.isPlainObject(c)?c:
{},h[b]=d.extend(r,g,e)):void 0!==e&&(h[b]=e));return h};d.extend({expando:"jQuery"+("2.2.1"+Math.random()).replace(/\D/g,""),isReady:!0,error:function(a){throw Error(a);},noop:function(){},isFunction:function(a){return"function"===d.type(a)},isArray:Array.isArray,isWindow:function(a){return null!=a&&a===a.window},isNumeric:function(a){var b=a&&a.toString();return!d.isArray(a)&&0<=b-parseFloat(b)+1},isPlainObject:function(a){return"object"!==d.type(a)||a.nodeType||d.isWindow(a)?!1:a.constructor&&
!Qa.call(a.constructor.prototype,"isPrototypeOf")?!1:!0},isEmptyObject:function(a){for(var b in a)return!1;return!0},type:function(a){return null==a?a+"":"object"==typeof a||"function"==typeof a?Da[Yb.call(a)]||"object":typeof a},globalEval:function(a){var b,c=eval;(a=d.trim(a))&&(1===a.indexOf("use strict")?(b=q.createElement("script"),b.text=a,q.head.appendChild(b).parentNode.removeChild(b)):c(a))},camelCase:function(a){return a.replace($b,"ms-").replace(ac,bc)},nodeName:function(a,b){return a.nodeName&&
a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,b){var c,d=0;if(K(a))for(c=a.length;c>d&&!1!==b.call(a[d],d,a[d]);d++);else for(d in a)if(!1===b.call(a[d],d,a[d]))break;return a},trim:function(a){return null==a?"":(a+"").replace(Zb,"")},makeArray:function(a,b){var c=b||[];return null!=a&&(K(Object(a))?d.merge(c,"string"==typeof a?[a]:a):Pa.call(c,a)),c},inArray:function(a,b,c){return null==b?-1:ua.call(b,a,c)},merge:function(a,b){for(var c=+b.length,d=0,f=a.length;c>d;d++)a[f++]=b[d];
return a.length=f,a},grep:function(a,b,c){for(var d=[],f=0,g=a.length,h=!c;g>f;f++)c=!b(a[f],f),c!==h&&d.push(a[f]);return d},map:function(a,b,c){var d,f,g=0,h=[];if(K(a))for(d=a.length;d>g;g++)f=b(a[g],g,c),null!=f&&h.push(f);else for(g in a)f=b(a[g],g,c),null!=f&&h.push(f);return eb.apply([],h)},guid:1,proxy:function(a,b){var c,e,f;return"string"==typeof b&&(c=a[b],b=a,a=c),d.isFunction(a)?(e=F.call(arguments,2),f=function(){return a.apply(b||this,e.concat(F.call(arguments)))},f.guid=a.guid=a.guid||
d.guid++,f):void 0},now:Date.now,support:w});"function"==typeof Symbol&&(d.fn[Symbol.iterator]=N[Symbol.iterator]);d.each("Boolean Number String Function Array Date RegExp Object Error Symbol".split(" "),function(a,b){Da["[object "+b+"]"]=b.toLowerCase()});var oa=function(a){function b(a,b,c,d){var e,f,g,h,k,l=b&&b.ownerDocument,m=b?b.nodeType:9;if(c=c||[],"string"!=typeof a||!a||1!==m&&9!==m&&11!==m)return c;if(!d&&((b?b.ownerDocument||b:G)!==x&&la(b),b=b||x,V)){if(11!==m&&(h=ta.exec(a)))if(e=h[1])if(9===
m){if(!(f=b.getElementById(e)))return c;if(f.id===e)return c.push(f),c}else{if(l&&(f=l.getElementById(e))&&xa(b,f)&&f.id===e)return c.push(f),c}else{if(h[2])return ma.apply(c,b.getElementsByTagName(a)),c;if((e=h[3])&&z.getElementsByClassName&&b.getElementsByClassName)return ma.apply(c,b.getElementsByClassName(e)),c}if(!(!z.qsa||O[a+" "]||E&&E.test(a))){if(1!==m)l=b,k=a;else if("object"!==b.nodeName.toLowerCase()){(g=b.getAttribute("id"))?g=g.replace(ua,"\\$&"):b.setAttribute("id",g=A);h=ya(a);e=h.length;
for(f=ia.test(g)?"#"+g:"[id='"+g+"']";e--;)h[e]=f+" "+n(h[e]);k=h.join(",");l=ga.test(a)&&p(b.parentNode)||b}if(k)try{return ma.apply(c,l.querySelectorAll(k)),c}catch(r){}finally{g===A&&b.removeAttribute("id")}}}return J(a.replace(U,"$1"),b,c,d)}function c(){function a(c,d){return b.push(c+" ")>t.cacheLength&&delete a[b.shift()],a[c+" "]=d}var b=[];return a}function d(a){return a[A]=!0,a}function f(a){var b=x.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}
function g(a,b){for(var c=a.split("|"),d=c.length;d--;)t.attrHandle[c[d]]=b}function h(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||-2147483648)-(~a.sourceIndex||-2147483648);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function k(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function l(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function r(a){return d(function(b){return b=
+b,d(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=f[g]]&&(c[e]=!(d[e]=c[e]))})})}function p(a){return a&&"undefined"!=typeof a.getElementsByTagName&&a}function m(){}function n(a){for(var b=0,c=a.length,d="";c>b;b++)d+=a[b].value;return d}function v(a,b,c){var d=b.dir,e=c&&"parentNode"===d,f=Q++;return b.first?function(b,c,f){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,f)}:function(b,c,g){var h,k,l,va=[ba,f];if(g)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,g))return!0}else for(;b=
b[d];)if(1===b.nodeType||e){if(l=b[A]||(b[A]={}),k=l[b.uniqueID]||(l[b.uniqueID]={}),(h=k[d])&&h[0]===ba&&h[1]===f)return va[2]=h[2];if(k[d]=va,va[2]=a(b,c,g))return!0}}}function q(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function w(a,b,c,d,e){for(var f,g=[],h=0,k=a.length,l=null!=b;k>h;h++)(f=a[h])&&(!c||c(f,d,e))&&(g.push(f),l&&b.push(h));return g}function y(a,c,f,g,h,k){return g&&!g[A]&&(g=y(g)),h&&!h[A]&&(h=y(h,k)),d(function(d,e,k,l){var m,
r,p=[],n=[],wb=e.length,t;if(!(t=d)){t=c||"*";for(var u=k.nodeType?[k]:k,v=[],q=0,x=u.length;x>q;q++)b(t,u[q],v);t=v}t=!a||!d&&c?t:w(t,p,a,k,l);u=f?h||(d?a:wb||g)?[]:e:t;if(f&&f(t,u,k,l),g)for(m=w(u,n),g(m,[],k,l),k=m.length;k--;)(r=m[k])&&(u[n[k]]=!(t[n[k]]=r));if(d){if(h||a){if(h){m=[];for(k=u.length;k--;)(r=u[k])&&m.push(t[k]=r);h(null,u=[],m,l)}for(k=u.length;k--;)(r=u[k])&&-1<(m=h?N(d,r):p[k])&&(d[m]=!(e[m]=r))}}else u=w(u===e?u.splice(wb,u.length):u),h?h(null,e,u,l):ma.apply(e,u)})}function D(a){var b,
c,d,e=a.length,f=t.relative[a[0].type];c=f||t.relative[" "];for(var g=f?1:0,h=v(function(a){return a===b},c,!0),k=v(function(a){return-1<N(b,a)},c,!0),l=[function(a,c,d){a=!f&&(d||c!==C)||((b=c).nodeType?h(a,c,d):k(a,c,d));return b=null,a}];e>g;g++)if(c=t.relative[a[g].type])l=[v(q(l),c)];else{if(c=t.filter[a[g].type].apply(null,a[g].matches),c[A]){for(d=++g;e>d&&!t.relative[a[d].type];d++);return y(1<g&&q(l),1<g&&n(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(U,"$1"),c,d>g&&D(a.slice(g,
d)),e>d&&D(a=a.slice(d)),e>d&&n(a))}l.push(c)}return q(l)}function K(a,c){var f=0<c.length,g=0<a.length,h=function(d,e,h,k,l){var m,r,p,n=0,u="0",Ea=d&&[],v=[],q=C,W=d||g&&t.find.TAG("*",l),fb=ba+=null==q?1:Math.random()||.1,A=W.length;for(l&&(C=e===x||e||l);u!==A&&null!=(m=W[u]);u++){if(g&&m){r=0;for(e||m.ownerDocument===x||(la(m),h=!V);p=a[r++];)if(p(m,e||x,h)){k.push(m);break}l&&(ba=fb)}f&&((m=!p&&m)&&n--,d&&Ea.push(m))}if(n+=u,f&&u!==n){for(r=0;p=c[r++];)p(Ea,v,e,h);if(d){if(0<n)for(;u--;)Ea[u]||
v[u]||(v[u]=ca.call(k));v=w(v)}ma.apply(k,v);l&&!d&&0<v.length&&1<n+c.length&&b.uniqueSort(k)}return l&&(ba=fb,C=q),Ea};return f?d(h):h}var L,z,t,W,xb,ya,B,J,C,na,wa,la,x,H,V,E,I,M,xa,A="sizzle"+1*new Date,G=a.document,ba=0,Q=0,P=c(),R=c(),O=c(),T=function(a,b){return a===b&&(wa=!0),0},Y={}.hasOwnProperty,F=[],ca=F.pop,da=F.push,ma=F.push,aa=F.slice,N=function(a,b){for(var c=0,d=a.length;d>c;c++)if(a[c]===b)return c;return-1},ha=RegExp("[\\x20\\t\\r\\n\\f]+","g"),U=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$",
"g"),ja=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,ka=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,oa=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*?)[\\x20\\t\\r\\n\\f]*\\]","g"),pa=/:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,ia=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,
Z={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:/^\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\]/,PSEUDO:/^:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,
CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},ra=/^(?:input|select|textarea|button)$/i,sa=/^h\d$/i,X=/^[^{]+\{\s*\[native \w/,
ta=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ga=/[+~]/,ua=/'|\\/g,ea=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)","ig"),fa=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,1023&a|56320)},qa=function(){la()};try{ma.apply(F=aa.call(G.childNodes),G.childNodes),F[G.childNodes.length].nodeType}catch(Ac){ma={apply:F.length?function(a,b){da.apply(a,aa.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=
c-1}}}z=b.support={};xb=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};la=b.setDocument=function(a){var b,c;a=a?a.ownerDocument||a:G;return a!==x&&9===a.nodeType&&a.documentElement?(x=a,H=x.documentElement,V=!xb(x),(c=x.defaultView)&&c.top!==c&&(c.addEventListener?c.addEventListener("unload",qa,!1):c.attachEvent&&c.attachEvent("onunload",qa)),z.attributes=f(function(a){return a.className="i",!a.getAttribute("className")}),z.getElementsByTagName=f(function(a){return a.appendChild(x.createComment("")),
!a.getElementsByTagName("*").length}),z.getElementsByClassName=X.test(x.getElementsByClassName),z.getById=f(function(a){return H.appendChild(a).id=A,!x.getElementsByName||!x.getElementsByName(A).length}),z.getById?(t.find.ID=function(a,b){if("undefined"!=typeof b.getElementById&&V){var c=b.getElementById(a);return c?[c]:[]}},t.filter.ID=function(a){var b=a.replace(ea,fa);return function(a){return a.getAttribute("id")===b}}):(delete t.find.ID,t.filter.ID=function(a){var b=a.replace(ea,fa);return function(a){return(a=
"undefined"!=typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}}),t.find.TAG=z.getElementsByTagName?function(a,b){return"undefined"!=typeof b.getElementsByTagName?b.getElementsByTagName(a):z.qsa?b.querySelectorAll(a):void 0}:function(a,b){var c,d=[],e=0,f=b.getElementsByTagName(a);if("*"===a){for(;c=f[e++];)1===c.nodeType&&d.push(c);return d}return f},t.find.CLASS=z.getElementsByClassName&&function(a,b){return"undefined"!=typeof b.getElementsByClassName&&V?b.getElementsByClassName(a):
void 0},I=[],E=[],(z.qsa=X.test(x.querySelectorAll))&&(f(function(a){H.appendChild(a).innerHTML="<a id='"+A+"'></a><select id='"+A+"-\r\\' msallowcapture=''><option selected=''></option></select>";a.querySelectorAll("[msallowcapture^='']").length&&E.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||E.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll("[id~="+A+"-]").length||E.push("~=");a.querySelectorAll(":checked").length||E.push(":checked");a.querySelectorAll("a#"+A+"+*").length||E.push(".#.+[+~]")}),f(function(a){var b=x.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&E.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||E.push(":enabled",":disabled");a.querySelectorAll("*,:x");E.push(",.*:")})),(z.matchesSelector=
X.test(M=H.matches||H.webkitMatchesSelector||H.mozMatchesSelector||H.oMatchesSelector||H.msMatchesSelector))&&f(function(a){z.disconnectedMatch=M.call(a,"div");M.call(a,"[s!='']:x");I.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")}),
E=E.length&&new RegExp(E.join("|")),I=I.length&&new RegExp(I.join("|")),b=X.test(H.compareDocumentPosition),xa=b||X.test(H.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||1!==d.nodeType||!(c.contains?c.contains(d):a.compareDocumentPosition&&16&a.compareDocumentPosition(d)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1},T=b?function(a,b){if(a===b)return wa=!0,0;var c=!a.compareDocumentPosition-!b.compareDocumentPosition;
return c?c:(c=(a.ownerDocument||a)===(b.ownerDocument||b)?a.compareDocumentPosition(b):1,1&c||!z.sortDetached&&b.compareDocumentPosition(a)===c?a===x||a.ownerDocument===G&&xa(G,a)?-1:b===x||b.ownerDocument===G&&xa(G,b)?1:na?N(na,a)-N(na,b):0:4&c?-1:1)}:function(a,b){if(a===b)return wa=!0,0;var c,d=0;c=a.parentNode;var e=b.parentNode,f=[a],g=[b];if(!c||!e)return a===x?-1:b===x?1:c?-1:e?1:na?N(na,a)-N(na,b):0;if(c===e)return h(a,b);for(c=a;c=c.parentNode;)f.unshift(c);for(c=b;c=c.parentNode;)g.unshift(c);
for(;f[d]===g[d];)d++;return d?h(f[d],g[d]):f[d]===G?-1:g[d]===G?1:0},x):x};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){if((a.ownerDocument||a)!==x&&la(a),c=c.replace(oa,"='$1']"),!(!z.matchesSelector||!V||O[c+" "]||I&&I.test(c)||E&&E.test(c)))try{var d=M.call(a,c);if(d||z.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(e){}return 0<b(c,x,null,[a]).length};b.contains=function(a,b){return(a.ownerDocument||a)!==x&&la(a),xa(a,b)};b.attr=function(a,
b){(a.ownerDocument||a)!==x&&la(a);var c=t.attrHandle[b.toLowerCase()],c=c&&Y.call(t.attrHandle,b.toLowerCase())?c(a,b,!V):void 0;return void 0!==c?c:z.attributes||!V?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;if(wa=!z.detectDuplicates,na=!z.sortStable&&a.slice(0),a.sort(T),wa){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}return na=
null,a};W=b.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"==typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=W(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=W(b);return c};t=b.selectors={cacheLength:50,createPseudo:d,match:Z,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){return a[1]=
a[1].replace(ea,fa),a[3]=(a[3]||a[4]||a[5]||"").replace(ea,fa),"~="===a[2]&&(a[3]=" "+a[3]+" "),a.slice(0,4)},CHILD:function(a){return a[1]=a[1].toLowerCase(),"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]),a},PSEUDO:function(a){var b,c=!a[6]&&a[2];return Z.CHILD.test(a[0])?null:(a[3]?a[2]=a[4]||a[5]||"":c&&pa.test(c)&&(b=ya(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length)&&(a[0]=a[0].slice(0,
b),a[2]=c.slice(0,b)),a.slice(0,3))}},filter:{TAG:function(a){var b=a.replace(ea,fa).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=P[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&P(a,function(a){return b.test("string"==typeof a.className&&a.className||"undefined"!=typeof a.getAttribute&&a.getAttribute("class")||"")})},ATTR:function(a,c,d){return function(e){e=b.attr(e,
a);return null==e?"!="===c:c?(e+="","="===c?e===d:"!="===c?e!==d:"^="===c?d&&0===e.indexOf(d):"*="===c?d&&-1<e.indexOf(d):"$="===c?d&&e.slice(-d.length)===d:"~="===c?-1<(" "+e.replace(ha," ")+" ").indexOf(d):"|="===c?e===d||e.slice(0,d.length+1)===d+"-":!1):!0}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,k){var l,m,r,p,n,u;c=f!==g?"nextSibling":"previousSibling";var t=b.parentNode,va=
h&&b.nodeName.toLowerCase();k=!k&&!h;var S=!1;if(t){if(f){for(;c;){for(p=b;p=p[c];)if(h?p.nodeName.toLowerCase()===va:1===p.nodeType)return!1;u=c="only"===a&&!u&&"nextSibling"}return!0}if(u=[g?t.firstChild:t.lastChild],g&&k)for(p=t,r=p[A]||(p[A]={}),m=r[p.uniqueID]||(r[p.uniqueID]={}),l=m[a]||[],S=(n=l[0]===ba&&l[1])&&l[2],p=n&&t.childNodes[n];p=++n&&p&&p[c]||(S=n=0)||u.pop();){if(1===p.nodeType&&++S&&p===b){m[a]=[ba,n,S];break}}else if(k&&(p=b,r=p[A]||(p[A]={}),m=r[p.uniqueID]||(r[p.uniqueID]={}),
l=m[a]||[],n=l[0]===ba&&l[1],S=n),!1===S)for(;(p=++n&&p&&p[c]||(S=n=0)||u.pop())&&((h?p.nodeName.toLowerCase()!==va:1!==p.nodeType)||!++S||(k&&(r=p[A]||(p[A]={}),m=r[p.uniqueID]||(r[p.uniqueID]={}),m[a]=[ba,S]),p!==b)););return S-=e,S===d||0===S%d&&0<=S/d}}},PSEUDO:function(a,c){var f,g=t.pseudos[a]||t.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);return g[A]?g(c):1<g.length?(f=[a,a,"",c],t.setFilters.hasOwnProperty(a.toLowerCase())?d(function(a,b){for(var d,e=g(a,c),f=e.length;f--;)d=
N(a,e[f]),a[d]=!(b[d]=e[f])}):function(a){return g(a,0,f)}):g}},pseudos:{not:d(function(a){var b=[],c=[],f=B(a.replace(U,"$1"));return f[A]?d(function(a,b,c,d){var e;c=f(a,null,d,[]);for(d=a.length;d--;)(e=c[d])&&(a[d]=!(b[d]=e))}):function(a,d,e){return b[0]=a,f(b,null,e,c),b[0]=null,!c.pop()}}),has:d(function(a){return function(c){return 0<b(a,c).length}}),contains:d(function(a){return a=a.replace(ea,fa),function(b){return-1<(b.textContent||b.innerText||W(b)).indexOf(a)}}),lang:d(function(a){return ia.test(a||
"")||b.error("unsupported lang: "+a),a=a.replace(ea,fa).toLowerCase(),function(b){var c;do if(c=V?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===H},focus:function(a){return a===x.activeElement&&(!x.hasFocus||x.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:function(a){return!1===
a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){return a.parentNode&&a.parentNode.selectedIndex,!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!t.pseudos.empty(a)},header:function(a){return sa.test(a.nodeName)},input:function(a){return ra.test(a.nodeName)},button:function(a){var b=
a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:r(function(){return[0]}),last:r(function(a,b){return[b-1]}),eq:r(function(a,b,c){return[0>c?c+b:c]}),even:r(function(a,b){for(var c=0;b>c;c+=2)a.push(c);return a}),odd:r(function(a,b){for(var c=1;b>c;c+=2)a.push(c);return a}),lt:r(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);
return a}),gt:r(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};t.pseudos.nth=t.pseudos.eq;for(L in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})t.pseudos[L]=k(L);for(L in{submit:!0,reset:!0})t.pseudos[L]=l(L);m.prototype=t.filters=t.pseudos;t.setFilters=new m;ya=b.tokenize=function(a,c){var d,e,f,g,h,k,l;if(h=R[a+" "])return c?0:h.slice(0);h=a;k=[];for(l=t.preFilter;h;){d&&!(e=ja.exec(h))||(e&&(h=h.slice(e[0].length)||h),k.push(f=[]));d=!1;(e=ka.exec(h))&&(d=e.shift(),f.push({value:d,
type:e[0].replace(U," ")}),h=h.slice(d.length));for(g in t.filter)!(e=Z[g].exec(h))||l[g]&&!(e=l[g](e))||(d=e.shift(),f.push({value:d,type:g,matches:e}),h=h.slice(d.length));if(!d)break}return c?h.length:h?b.error(a):R(a,k).slice(0)};return B=b.compile=function(a,b){var c,d=[],e=[],f=O[a+" "];if(!f){b||(b=ya(a));for(c=b.length;c--;)f=D(b[c]),f[A]?d.push(f):e.push(f);f=O(a,K(e,d));f.selector=a}return f},J=b.select=function(a,b,c,d){var e,f,g,h,k,l="function"==typeof a&&a,m=!d&&ya(a=l.selector||a);
if(c=c||[],1===m.length){if(f=m[0]=m[0].slice(0),2<f.length&&"ID"===(g=f[0]).type&&z.getById&&9===b.nodeType&&V&&t.relative[f[1].type]){if(b=(t.find.ID(g.matches[0].replace(ea,fa),b)||[])[0],!b)return c;l&&(b=b.parentNode);a=a.slice(f.shift().value.length)}for(e=Z.needsContext.test(a)?0:f.length;e--&&(g=f[e],!t.relative[h=g.type]);)if((k=t.find[h])&&(d=k(g.matches[0].replace(ea,fa),ga.test(f[0].type)&&p(b.parentNode)||b))){if(f.splice(e,1),a=d.length&&n(f),!a)return ma.apply(c,d),c;break}}return(l||
B(a,m))(d,b,!V,c,!b||ga.test(a)&&p(b.parentNode)||b),c},z.sortStable=A.split("").sort(T).join("")===A,z.detectDuplicates=!!wa,la(),z.sortDetached=f(function(a){return 1&a.compareDocumentPosition(x.createElement("div"))}),f(function(a){return a.innerHTML="<a href='#'></a>","#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,b,c){return c?void 0:a.getAttribute(b,"type"===b.toLowerCase()?1:2)}),z.attributes&&f(function(a){return a.innerHTML="<input/>",a.firstChild.setAttribute("value",
""),""===a.firstChild.getAttribute("value")})||g("value",function(a,b,c){return c||"input"!==a.nodeName.toLowerCase()?void 0:a.defaultValue}),f(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;return c?void 0:!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null}),b}(n);d.find=oa;d.expr=oa.selectors;d.expr[":"]=d.expr.pseudos;
d.uniqueSort=d.unique=oa.uniqueSort;d.text=oa.getText;d.isXMLDoc=oa.isXML;d.contains=oa.contains;var pa=function(a,b,c){for(var e=[],f=void 0!==c;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&d(a).is(c))break;e.push(a)}return e},yb=function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c},zb=d.expr.match.needsContext,Ab=/^<([\w-]+)\s*\/?>(?:<\/\1>|)$/,Ob=/^.[^:#\[\.,]*$/;d.filter=function(a,b,c){var e=b[0];return c&&(a=":not("+a+")"),1===b.length&&1===e.nodeType?
d.find.matchesSelector(e,a)?[e]:[]:d.find.matches(a,d.grep(b,function(a){return 1===a.nodeType}))};d.fn.extend({find:function(a){var b,c=this.length,e=[],f=this;if("string"!=typeof a)return this.pushStack(d(a).filter(function(){for(b=0;c>b;b++)if(d.contains(f[b],this))return!0}));for(b=0;c>b;b++)d.find(a,f[b],e);return e=this.pushStack(1<c?d.unique(e):e),e.selector=this.selector?this.selector+" "+a:a,e},filter:function(a){return this.pushStack(B(this,a||[],!1))},not:function(a){return this.pushStack(B(this,
a||[],!0))},is:function(a){return!!B(this,"string"==typeof a&&zb.test(a)?d(a):a||[],!1).length}});var Bb,cc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]*))$/;(d.fn.init=function(a,b,c){var e,f;if(!a)return this;if(c=c||Bb,"string"==typeof a){if(e="<"===a[0]&&">"===a[a.length-1]&&3<=a.length?[null,a,null]:cc.exec(a),!e||!e[1]&&b)return!b||b.jquery?(b||c).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof d?b[0]:b,d.merge(this,d.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:q,!0)),Ab.test(e[1])&&
d.isPlainObject(b))for(e in b)d.isFunction(this[e])?this[e](b[e]):this.attr(e,b[e]);return this}return f=q.getElementById(e[2]),f&&f.parentNode&&(this.length=1,this[0]=f),this.context=q,this.selector=a,this}return a.nodeType?(this.context=this[0]=a,this.length=1,this):d.isFunction(a)?void 0!==c.ready?c.ready(a):a(d):(void 0!==a.selector&&(this.selector=a.selector,this.context=a.context),d.makeArray(a,this))}).prototype=d.fn;Bb=d(q);var dc=/^(?:parents|prev(?:Until|All))/,ec={children:!0,contents:!0,
next:!0,prev:!0};d.fn.extend({has:function(a){var b=d(a,this),c=b.length;return this.filter(function(){for(var a=0;c>a;a++)if(d.contains(this,b[a]))return!0})},closest:function(a,b){for(var c,e=0,f=this.length,g=[],h=zb.test(a)||"string"!=typeof a?d(a,b||this.context):0;f>e;e++)for(c=this[e];c&&c!==b;c=c.parentNode)if(11>c.nodeType&&(h?-1<h.index(c):1===c.nodeType&&d.find.matchesSelector(c,a))){g.push(c);break}return this.pushStack(1<g.length?d.uniqueSort(g):g)},index:function(a){return a?"string"==
typeof a?ua.call(d(a),this[0]):ua.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){return this.pushStack(d.uniqueSort(d.merge(this.get(),d(a,b))))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});d.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return pa(a,"parentNode")},parentsUntil:function(a,b,c){return pa(a,"parentNode",c)},next:function(a){return O(a,
"nextSibling")},prev:function(a){return O(a,"previousSibling")},nextAll:function(a){return pa(a,"nextSibling")},prevAll:function(a){return pa(a,"previousSibling")},nextUntil:function(a,b,c){return pa(a,"nextSibling",c)},prevUntil:function(a,b,c){return pa(a,"previousSibling",c)},siblings:function(a){return yb((a.parentNode||{}).firstChild,a)},children:function(a){return yb(a.firstChild)},contents:function(a){return a.contentDocument||d.merge([],a.childNodes)}},function(a,b){d.fn[a]=function(c,e){var f=
d.map(this,b,c);return"Until"!==a.slice(-5)&&(e=c),e&&"string"==typeof e&&(f=d.filter(e,f)),1<this.length&&(ec[a]||d.uniqueSort(f),dc.test(a)&&f.reverse()),this.pushStack(f)}});var P=/\S+/g;d.Callbacks=function(a){a="string"==typeof a?qa(a):d.extend({},a);var b,c,e,f,g=[],h=[],k=-1,l=function(){f=a.once;for(e=b=!0;h.length;k=-1)for(c=h.shift();++k<g.length;)!1===g[k].apply(c[0],c[1])&&a.stopOnFalse&&(k=g.length,c=!1);a.memory||(c=!1);b=!1;f&&(g=c?[]:"")},r={add:function(){return g&&(c&&!b&&(k=g.length-
1,h.push(c)),function m(b){d.each(b,function(b,c){d.isFunction(c)?a.unique&&r.has(c)||g.push(c):c&&c.length&&"string"!==d.type(c)&&m(c)})}(arguments),c&&!b&&l()),this},remove:function(){return d.each(arguments,function(a,b){for(var c;-1<(c=d.inArray(b,g,c));)g.splice(c,1),k>=c&&k--}),this},has:function(a){return a?-1<d.inArray(a,g):0<g.length},empty:function(){return g&&(g=[]),this},disable:function(){return f=h=[],g=c="",this},disabled:function(){return!g},lock:function(){return f=h=[],c||(g=c=""),
this},locked:function(){return!!f},fireWith:function(a,c){return f||(c=c||[],c=[a,c.slice?c.slice():c],h.push(c),b||l()),this},fire:function(){return r.fireWith(this,arguments),this},fired:function(){return!!e}};return r};d.extend({Deferred:function(a){var b=[["resolve","done",d.Callbacks("once memory"),"resolved"],["reject","fail",d.Callbacks("once memory"),"rejected"],["notify","progress",d.Callbacks("memory")]],c="pending",e={state:function(){return c},always:function(){return f.done(arguments).fail(arguments),
this},then:function(){var a=arguments;return d.Deferred(function(c){d.each(b,function(b,l){var r=d.isFunction(a[b])&&a[b];f[l[1]](function(){var a=r&&r.apply(this,arguments);a&&d.isFunction(a.promise)?a.promise().progress(c.notify).done(c.resolve).fail(c.reject):c[l[0]+"With"](this===e?c.promise():this,r?[a]:arguments)})});a=null}).promise()},promise:function(a){return null!=a?d.extend(a,e):e}},f={};return e.pipe=e.then,d.each(b,function(a,d){var k=d[2],l=d[3];e[d[1]]=k.add;l&&k.add(function(){c=
l},b[1^a][2].disable,b[2][2].lock);f[d[0]]=function(){return f[d[0]+"With"](this===f?e:this,arguments),this};f[d[0]+"With"]=k.fireWith}),e.promise(f),a&&a.call(f,f),f},when:function(a){var b=0,c=F.call(arguments),e=c.length,f=1!==e||a&&d.isFunction(a.promise)?e:0,g=1===f?a:d.Deferred(),h=function(a,b,c){return function(d){b[a]=this;c[a]=1<arguments.length?F.call(arguments):d;c===k?g.notifyWith(b,c):--f||g.resolveWith(b,c)}},k,l,r;if(1<e)for(k=Array(e),l=Array(e),r=Array(e);e>b;b++)c[b]&&d.isFunction(c[b].promise)?
c[b].promise().progress(h(b,l,k)).done(h(b,r,c)).fail(g.reject):--f;return f||g.resolveWith(r,c),g.promise()}});var Fa;d.fn.ready=function(a){return d.ready.promise().done(a),this};d.extend({isReady:!1,readyWait:1,holdReady:function(a){a?d.readyWait++:d.ready(!0)},ready:function(a){(!0===a?--d.readyWait:d.isReady)||(d.isReady=!0,!0!==a&&0<--d.readyWait||(Fa.resolveWith(q,[d]),d.fn.triggerHandler&&(d(q).triggerHandler("ready"),d(q).off("ready"))))}});d.ready.promise=function(a){return Fa||(Fa=d.Deferred(),
"complete"===q.readyState||"loading"!==q.readyState&&!q.documentElement.doScroll?n.setTimeout(d.ready):(q.addEventListener("DOMContentLoaded",ha),n.addEventListener("load",ha))),Fa.promise(a)};d.ready.promise();var T=function(a,b,c,e,f,g,h){var k=0,l=a.length,r=null==c;if("object"===d.type(c))for(k in f=!0,c)T(a,b,k,c[k],!0,g,h);else if(void 0!==e&&(f=!0,d.isFunction(e)||(h=!0),r&&(h?(b.call(a,e),b=null):(r=b,b=function(a,b,c){return r.call(d(a),c)})),b))for(;l>k;k++)b(a[k],c,h?e:e.call(a[k],k,b(a[k],
c)));return f?a:r?b.call(a):l?b(a[0],c):g},ra=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};Y.uid=1;Y.prototype={register:function(a,b){var c=b||{};return a.nodeType?a[this.expando]=c:Object.defineProperty(a,this.expando,{value:c,writable:!0,configurable:!0}),a[this.expando]},cache:function(a){if(!ra(a))return{};var b=a[this.expando];return b||(b={},ra(a)&&(a.nodeType?a[this.expando]=b:Object.defineProperty(a,this.expando,{value:b,configurable:!0}))),b},set:function(a,b,c){var d;
a=this.cache(a);if("string"==typeof b)a[b]=c;else for(d in b)a[d]=b[d];return a},get:function(a,b){return void 0===b?this.cache(a):a[this.expando]&&a[this.expando][b]},access:function(a,b,c){var e;return void 0===b||b&&"string"==typeof b&&void 0===c?(e=this.get(a,b),void 0!==e?e:this.get(a,d.camelCase(b))):(this.set(a,b,c),void 0!==c?c:b)},remove:function(a,b){var c,e,f=a[this.expando];if(void 0!==f){if(void 0===b)this.register(a);else for(d.isArray(b)?e=b.concat(b.map(d.camelCase)):(c=d.camelCase(b),
b in f?e=[b,c]:(e=c,e=e in f?[e]:e.match(P)||[])),c=e.length;c--;)delete f[e[c]];(void 0===b||d.isEmptyObject(f))&&(a.nodeType?a[this.expando]=void 0:delete a[this.expando])}},hasData:function(a){a=a[this.expando];return void 0!==a&&!d.isEmptyObject(a)}};var v=new Y,D=new Y,Pb=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,Xa=/[A-Z]/g;d.extend({hasData:function(a){return D.hasData(a)||v.hasData(a)},data:function(a,b,c){return D.access(a,b,c)},removeData:function(a,b){D.remove(a,b)},_data:function(a,b,c){return v.access(a,
b,c)},_removeData:function(a,b){v.remove(a,b)}});d.fn.extend({data:function(a,b){var c,e,f,g=this[0],h=g&&g.attributes;if(void 0===a){if(this.length&&(f=D.get(g),1===g.nodeType&&!v.get(g,"hasDataAttrs"))){for(c=h.length;c--;)h[c]&&(e=h[c].name,0===e.indexOf("data-")&&(e=d.camelCase(e.slice(5)),M(g,e,f[e])));v.set(g,"hasDataAttrs",!0)}return f}return"object"==typeof a?this.each(function(){D.set(this,a)}):T(this,function(b){var c,e;if(g&&void 0===b){if((c=D.get(g,a)||D.get(g,a.replace(Xa,"-$&").toLowerCase()),
void 0!==c)||(e=d.camelCase(a),c=D.get(g,e),void 0!==c)||(c=M(g,e,void 0),void 0!==c))return c}else e=d.camelCase(a),this.each(function(){var c=D.get(this,e);D.set(this,e,b);-1<a.indexOf("-")&&void 0!==c&&D.set(this,a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){D.remove(this,a)})}});d.extend({queue:function(a,b,c){var e;return a?(b=(b||"fx")+"queue",e=v.get(a,b),c&&(!e||d.isArray(c)?e=v.access(a,b,d.makeArray(c)):e.push(c)),e||[]):void 0},dequeue:function(a,
b){b=b||"fx";var c=d.queue(a,b),e=c.length,f=c.shift(),g=d._queueHooks(a,b),h=function(){d.dequeue(a,b)};"inprogress"===f&&(f=c.shift(),e--);f&&("fx"===b&&c.unshift("inprogress"),delete g.stop,f.call(a,h,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var c=b+"queueHooks";return v.get(a,c)||v.access(a,c,{empty:d.Callbacks("once memory").add(function(){v.remove(a,[b+"queue",c])})})}});d.fn.extend({queue:function(a,b){var c=2;return"string"!=typeof a&&(b=a,a="fx",c--),arguments.length<c?d.queue(this[0],
a):void 0===b?this:this.each(function(){var c=d.queue(this,a,b);d._queueHooks(this,a);"fx"===a&&"inprogress"!==c[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var c,e=1,f=d.Deferred(),g=this,h=this.length,k=function(){--e||f.resolveWith(g,[g])};"string"!=typeof a&&(b=a,a=void 0);for(a=a||"fx";h--;)(c=v.get(g[h],a+"queueHooks"))&&c.empty&&(e++,c.empty.add(k));return k(),f.promise(b)}});
var Cb=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,ia=new RegExp("^(?:([+-])=|)("+Cb+")([a-z%]*)$","i"),da=["Top","Right","Bottom","Left"],Z=function(a,b){return a=b||a,"none"===d.css(a,"display")||!d.contains(a.ownerDocument,a)},Db=/^(?:checkbox|radio)$/i,$a=/<([\w:-]+)/,ab=/^$|\/(?:java|ecma)script/i,Q={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>",
"</tr></tbody></table>"],_default:[0,"",""]};Q.optgroup=Q.option;Q.tbody=Q.tfoot=Q.colgroup=Q.caption=Q.thead;Q.th=Q.td;var Qb=/<|&#?\w+;/;!function(){var a=q.createDocumentFragment().appendChild(q.createElement("div")),b=q.createElement("input");b.setAttribute("type","radio");b.setAttribute("checked","checked");b.setAttribute("name","t");a.appendChild(b);w.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML="<textarea>x</textarea>";w.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue}();
var fc=/^key/,gc=/^(?:mouse|pointer|contextmenu|drag|drop)|click/,Eb=/^([^.]*)(?:\.(.+)|)/;d.event={global:{},add:function(a,b,c,e,f){var g,h,k,l,r,p,m,n,q,w;if(r=v.get(a))for(c.handler&&(g=c,c=g.handler,f=g.selector),c.guid||(c.guid=d.guid++),(l=r.events)||(l=r.events={}),(h=r.handle)||(h=r.handle=function(b){return"undefined"!=typeof d&&d.event.triggered!==b.type?d.event.dispatch.apply(a,arguments):void 0}),b=(b||"").match(P)||[""],r=b.length;r--;)k=Eb.exec(b[r])||[],q=w=k[1],k=(k[2]||"").split(".").sort(),
q&&(m=d.event.special[q]||{},q=(f?m.delegateType:m.bindType)||q,m=d.event.special[q]||{},p=d.extend({type:q,origType:w,data:e,handler:c,guid:c.guid,selector:f,needsContext:f&&d.expr.match.needsContext.test(f),namespace:k.join(".")},g),(n=l[q])||(n=l[q]=[],n.delegateCount=0,m.setup&&!1!==m.setup.call(a,e,k,h)||a.addEventListener&&a.addEventListener(q,h)),m.add&&(m.add.call(a,p),p.handler.guid||(p.handler.guid=c.guid)),f?n.splice(n.delegateCount++,0,p):n.push(p),d.event.global[q]=!0)},remove:function(a,
b,c,e,f){var g,h,k,l,n,p,m,u,q,w,y,D=v.hasData(a)&&v.get(a);if(D&&(l=D.events)){b=(b||"").match(P)||[""];for(n=b.length;n--;)if(k=Eb.exec(b[n])||[],q=y=k[1],w=(k[2]||"").split(".").sort(),q){m=d.event.special[q]||{};q=(e?m.delegateType:m.bindType)||q;u=l[q]||[];k=k[2]&&new RegExp("(^|\\.)"+w.join("\\.(?:.*\\.|)")+"(\\.|$)");for(h=g=u.length;g--;)p=u[g],!f&&y!==p.origType||c&&c.guid!==p.guid||k&&!k.test(p.namespace)||e&&e!==p.selector&&("**"!==e||!p.selector)||(u.splice(g,1),p.selector&&u.delegateCount--,
m.remove&&m.remove.call(a,p));h&&!u.length&&(m.teardown&&!1!==m.teardown.call(a,w,D.handle)||d.removeEvent(a,q,D.handle),delete l[q])}else for(q in l)d.event.remove(a,q+b[n],c,e,!0);d.isEmptyObject(l)&&v.remove(a,"handle events")}},dispatch:function(a){a=d.event.fix(a);var b,c,e,f,g,h=[],k=F.call(arguments);b=(v.get(this,"events")||{})[a.type]||[];var l=d.event.special[a.type]||{};if(k[0]=a,a.delegateTarget=this,!l.preDispatch||!1!==l.preDispatch.call(this,a)){h=d.event.handlers.call(this,a,b);for(b=
0;(f=h[b++])&&!a.isPropagationStopped();)for(a.currentTarget=f.elem,c=0;(g=f.handlers[c++])&&!a.isImmediatePropagationStopped();)a.rnamespace&&!a.rnamespace.test(g.namespace)||(a.handleObj=g,a.data=g.data,e=((d.event.special[g.origType]||{}).handle||g.handler).apply(f.elem,k),void 0===e||!1!==(a.result=e)||(a.preventDefault(),a.stopPropagation()));return l.postDispatch&&l.postDispatch.call(this,a),a.result}},handlers:function(a,b){var c,e,f,g,h=[],k=b.delegateCount,l=a.target;if(k&&l.nodeType&&("click"!==
a.type||isNaN(a.button)||1>a.button))for(;l!==this;l=l.parentNode||this)if(1===l.nodeType&&(!0!==l.disabled||"click"!==a.type)){e=[];for(c=0;k>c;c++)g=b[c],f=g.selector+" ",void 0===e[f]&&(e[f]=g.needsContext?-1<d(f,this).index(l):d.find(f,this,null,[l]).length),e[f]&&e.push(g);e.length&&h.push({elem:l,handlers:e})}return k<b.length&&h.push({elem:this,handlers:b.slice(k)}),h},props:"altKey bubbles cancelable ctrlKey currentTarget detail eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),
fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){return null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode),a}},mouseHooks:{props:"button buttons clientX clientY offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var c,d,f,g=b.button;return null==a.pageX&&null!=b.clientX&&(c=a.target.ownerDocument||q,d=c.documentElement,f=c.body,a.pageX=b.clientX+(d&&d.scrollLeft||f&&f.scrollLeft||0)-(d&&d.clientLeft||f&&f.clientLeft||
0),a.pageY=b.clientY+(d&&d.scrollTop||f&&f.scrollTop||0)-(d&&d.clientTop||f&&f.clientTop||0)),a.which||void 0===g||(a.which=1&g?1:2&g?3:4&g?2:0),a}},fix:function(a){if(a[d.expando])return a;var b,c,e;b=a.type;var f=a,g=this.fixHooks[b];g||(this.fixHooks[b]=g=gc.test(b)?this.mouseHooks:fc.test(b)?this.keyHooks:{});e=g.props?this.props.concat(g.props):this.props;a=new d.Event(f);for(b=e.length;b--;)c=e[b],a[c]=f[c];return a.target||(a.target=q),3===a.target.nodeType&&(a.target=a.target.parentNode),
g.filter?g.filter(a,f):a},special:{load:{noBubble:!0},focus:{trigger:function(){return this!==bb()&&this.focus?(this.focus(),!1):void 0},delegateType:"focusin"},blur:{trigger:function(){return this===bb()&&this.blur?(this.blur(),!1):void 0},delegateType:"focusout"},click:{trigger:function(){return"checkbox"===this.type&&this.click&&d.nodeName(this,"input")?(this.click(),!1):void 0},_default:function(a){return d.nodeName(a.target,"a")}},beforeunload:{postDispatch:function(a){void 0!==a.result&&a.originalEvent&&
(a.originalEvent.returnValue=a.result)}}}};d.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c)};d.Event=function(a,b){return this instanceof d.Event?(a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||void 0===a.defaultPrevented&&!1===a.returnValue?za:U):this.type=a,b&&d.extend(this,b),this.timeStamp=a&&a.timeStamp||d.now(),void(this[d.expando]=!0)):new d.Event(a,b)};d.Event.prototype={constructor:d.Event,isDefaultPrevented:U,isPropagationStopped:U,
isImmediatePropagationStopped:U,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=za;a&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=za;a&&a.stopPropagation()},stopImmediatePropagation:function(){var a=this.originalEvent;this.isImmediatePropagationStopped=za;a&&a.stopImmediatePropagation();this.stopPropagation()}};d.each({mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"},
function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(a){var e,f=a.relatedTarget,g=a.handleObj;return(!f||f!==this&&!d.contains(this,f))&&(a.type=g.origType,e=g.handler.apply(this,arguments),a.type=b),e}}});d.fn.extend({on:function(a,b,c,d){return Ia(this,a,b,c,d)},one:function(a,b,c,d){return Ia(this,a,b,c,d,1)},off:function(a,b,c){var e,f;if(a&&a.preventDefault&&a.handleObj)return e=a.handleObj,d(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,
e.handler),this;if("object"==typeof a){for(f in a)this.off(f,b,a[f]);return this}return(!1===b||"function"==typeof b)&&(c=b,b=void 0),!1===c&&(c=U),this.each(function(){d.event.remove(this,a,c,b)})}});var hc=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:-]+)[^>]*)\/>/gi,ic=/<script|<style|<link/i,Ub=/checked\s*(?:[^=]|=\s*.checked.)/i,Tb=/^true\/(.*)/,Vb=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g;d.extend({htmlPrefilter:function(a){return a.replace(hc,"<$1></$2>")},clone:function(a,b,
c){var e,f,g,h,k=a.cloneNode(!0),l=d.contains(a.ownerDocument,a);if(!(w.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||d.isXMLDoc(a)))for(h=J(k),g=J(a),e=0,f=g.length;f>e;e++){var n=g[e],p=h[e],m=p.nodeName.toLowerCase();"input"===m&&Db.test(n.type)?p.checked=n.checked:("input"===m||"textarea"===m)&&(p.defaultValue=n.defaultValue)}if(b)if(c)for(g=g||J(a),h=h||J(k),e=0,f=g.length;f>e;e++)db(g[e],h[e]);else db(a,k);return h=J(k,"script"),0<h.length&&Ha(h,!l&&J(a,"script")),k},cleanData:function(a){for(var b,
c,e,f=d.event.special,g=0;void 0!==(c=a[g]);g++)if(ra(c)){if(b=c[v.expando]){if(b.events)for(e in b.events)f[e]?d.event.remove(c,e):d.removeEvent(c,e,b.handle);c[v.expando]=void 0}c[D.expando]&&(c[D.expando]=void 0)}}});d.fn.extend({domManip:ca,detach:function(a){return gb(this,a,!0)},remove:function(a){return gb(this,a)},text:function(a){return T(this,function(a){return void 0===a?d.text(this):this.empty().each(function(){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||(this.textContent=
a)})},null,a,arguments.length)},append:function(){return ca(this,arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||cb(this,a).appendChild(a)})},prepend:function(){return ca(this,arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=cb(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return ca(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return ca(this,arguments,function(a){this.parentNode&&
this.parentNode.insertBefore(a,this.nextSibling)})},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(d.cleanData(J(a,!1)),a.textContent="");return this},clone:function(a,b){return a=null==a?!1:a,b=null==b?a:b,this.map(function(){return d.clone(this,a,b)})},html:function(a){return T(this,function(a){var c=this[0]||{},e=0,f=this.length;if(void 0===a&&1===c.nodeType)return c.innerHTML;if("string"==typeof a&&!ic.test(a)&&!Q[($a.exec(a)||["",""])[1].toLowerCase()]){a=d.htmlPrefilter(a);
try{for(;f>e;e++)c=this[e]||{},1===c.nodeType&&(d.cleanData(J(c,!1)),c.innerHTML=a);c=0}catch(g){}}c&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=[];return ca(this,arguments,function(b){var c=this.parentNode;0>d.inArray(this,a)&&(d.cleanData(J(this)),c&&c.replaceChild(b,this))},a)}});d.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(a){for(var e=[],f=d(a),g=f.length-1,
h=0;g>=h;h++)a=h===g?this:this.clone(!0),d(f[h])[b](a),Pa.apply(e,a.get());return this.pushStack(e)}});var Aa,ib={HTML:"block",BODY:"block"},jb=/^margin/,Ka=new RegExp("^("+Cb+")(?!px)[a-z%]+$","i"),Ba=function(a){var b=a.ownerDocument.defaultView;return b&&b.opener||(b=n),b.getComputedStyle(a)},Ra=function(a,b,c,d){var f,g={};for(f in b)g[f]=a.style[f],a.style[f]=b[f];c=c.apply(a,d||[]);for(f in b)a.style[f]=g[f];return c},sa=q.documentElement;!function(){var a,b,c,e,f=q.createElement("div"),g=q.createElement("div");
if(g.style){var h=function(){g.style.cssText="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;position:relative;display:block;margin:auto;border:1px;padding:1px;top:1%;width:50%";g.innerHTML="";sa.appendChild(f);var d=n.getComputedStyle(g);a="1%"!==d.top;e="2px"===d.marginLeft;b="4px"===d.width;g.style.marginRight="50%";c="4px"===d.marginRight;sa.removeChild(f)};g.style.backgroundClip="content-box";g.cloneNode(!0).style.backgroundClip="";w.clearCloneStyle="content-box"===
g.style.backgroundClip;f.style.cssText="border:0;width:8px;height:0;top:0;left:-9999px;padding:0;margin-top:1px;position:absolute";f.appendChild(g);d.extend(w,{pixelPosition:function(){return h(),a},boxSizingReliable:function(){return null==b&&h(),b},pixelMarginRight:function(){return null==b&&h(),c},reliableMarginLeft:function(){return null==b&&h(),e},reliableMarginRight:function(){var a,b=g.appendChild(q.createElement("div"));return b.style.cssText=g.style.cssText="-webkit-box-sizing:content-box;box-sizing:content-box;display:block;margin:0;border:0;padding:0",
b.style.marginRight=b.style.width="0",g.style.width="1px",sa.appendChild(f),a=!parseFloat(n.getComputedStyle(b).marginRight),sa.removeChild(f),g.removeChild(b),a}})}}();var jc=/^(none|table(?!-c[ea]).+)/,kc={position:"absolute",visibility:"hidden",display:"block"},Fb={letterSpacing:"0",fontWeight:"400"},mb=["Webkit","O","Moz","ms"],lb=q.createElement("div").style;d.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=ja(a,"opacity");return""===c?"1":c}}}},cssNumber:{animationIterationCount:!0,
columnCount:!0,fillOpacity:!0,flexGrow:!0,flexShrink:!0,fontWeight:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":"cssFloat"},style:function(a,b,c,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g,h,k=d.camelCase(b),l=a.style;return b=d.cssProps[k]||(d.cssProps[k]=kb(k)||k),h=d.cssHooks[b]||d.cssHooks[k],void 0===c?h&&"get"in h&&void 0!==(f=h.get(a,!1,e))?f:l[b]:(g=typeof c,"string"===g&&(f=ia.exec(c))&&f[1]&&(c=Ya(a,b,f),g="number"),null!=c&&
c===c&&("number"===g&&(c+=f&&f[3]||(d.cssNumber[k]?"":"px")),w.clearCloneStyle||""!==c||0!==b.indexOf("background")||(l[b]="inherit"),h&&"set"in h&&void 0===(c=h.set(a,c,e))||(l[b]=c)),void 0)}},css:function(a,b,c,e){var f,g,h,k=d.camelCase(b);return b=d.cssProps[k]||(d.cssProps[k]=kb(k)||k),h=d.cssHooks[b]||d.cssHooks[k],h&&"get"in h&&(f=h.get(a,!0,c)),void 0===f&&(f=ja(a,b,e)),"normal"===f&&b in Fb&&(f=Fb[b]),""===c||c?(g=parseFloat(f),!0===c||isFinite(g)?g||0:f):f}});d.each(["height","width"],
function(a,b){d.cssHooks[b]={get:function(a,e,f){return e?jc.test(d.css(a,"display"))&&0===a.offsetWidth?Ra(a,kc,function(){return pb(a,b,f)}):pb(a,b,f):void 0},set:function(a,e,f){var g,h=f&&Ba(a);f=f&&ob(a,b,f,"border-box"===d.css(a,"boxSizing",!1,h),h);return f&&(g=ia.exec(e))&&"px"!==(g[3]||"px")&&(a.style[b]=e,e=d.css(a,b)),nb(a,e,f)}}});d.cssHooks.marginLeft=La(w.reliableMarginLeft,function(a,b){return b?(parseFloat(ja(a,"marginLeft"))||a.getBoundingClientRect().left-Ra(a,{marginLeft:0},function(){return a.getBoundingClientRect().left}))+
"px":void 0});d.cssHooks.marginRight=La(w.reliableMarginRight,function(a,b){return b?Ra(a,{display:"inline-block"},ja,[a,"marginRight"]):void 0});d.each({margin:"",padding:"",border:"Width"},function(a,b){d.cssHooks[a+b]={expand:function(c){var d=0,f={};for(c="string"==typeof c?c.split(" "):[c];4>d;d++)f[a+da[d]+b]=c[d]||c[d-2]||c[0];return f}};jb.test(a)||(d.cssHooks[a+b].set=nb)});d.fn.extend({css:function(a,b){return T(this,function(a,b,f){var g,h={},k=0;if(d.isArray(b)){f=Ba(a);for(g=b.length;g>
k;k++)h[b[k]]=d.css(a,b[k],!1,f);return h}return void 0!==f?d.style(a,b,f):d.css(a,b)},a,b,1<arguments.length)},show:function(){return qb(this,!0)},hide:function(){return qb(this)},toggle:function(a){return"boolean"==typeof a?a?this.show():this.hide():this.each(function(){Z(this)?d(this).show():d(this).hide()})}});d.Tween=C;C.prototype={constructor:C,init:function(a,b,c,e,f,g){this.elem=a;this.prop=c;this.easing=f||d.easing._default;this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=
g||(d.cssNumber[c]?"":"px")},cur:function(){var a=C.propHooks[this.prop];return a&&a.get?a.get(this):C.propHooks._default.get(this)},run:function(a){var b,c=C.propHooks[this.prop];return this.options.duration?this.pos=b=d.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):this.pos=b=a,this.now=(this.end-this.start)*b+this.start,this.options.step&&this.options.step.call(this.elem,this.now,this),c&&c.set?c.set(this):C.propHooks._default.set(this),this}};C.prototype.init.prototype=
C.prototype;C.propHooks={_default:{get:function(a){var b;return 1!==a.elem.nodeType||null!=a.elem[a.prop]&&null==a.elem.style[a.prop]?a.elem[a.prop]:(b=d.css(a.elem,a.prop,""),b&&"auto"!==b?b:0)},set:function(a){d.fx.step[a.prop]?d.fx.step[a.prop](a):1!==a.elem.nodeType||null==a.elem.style[d.cssProps[a.prop]]&&!d.cssHooks[a.prop]?a.elem[a.prop]=a.now:d.style(a.elem,a.prop,a.now+a.unit)}}};C.propHooks.scrollTop=C.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=
a.now)}};d.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2},_default:"swing"};d.fx=C.prototype.init;d.fx.step={};var ka,Ga,lc=/^(?:toggle|show|hide)$/,mc=/queueHooks$/;d.Animation=d.extend(R,{tweeners:{"*":[function(a,b){var c=this.createTween(a,b);return Ya(c.elem,a,ia.exec(b),c),c}]},tweener:function(a,b){d.isFunction(a)?(b=a,a=["*"]):a=a.match(P);for(var c,e=0,f=a.length;f>e;e++)c=a[e],R.tweeners[c]=R.tweeners[c]||[],R.tweeners[c].unshift(b)},prefilters:[function(a,
b,c){var e,f,g,h,k,l,n,p=this,m={},u=a.style,q=a.nodeType&&Z(a),w=v.get(a,"fxshow");c.queue||(h=d._queueHooks(a,"fx"),null==h.unqueued&&(h.unqueued=0,k=h.empty.fire,h.empty.fire=function(){h.unqueued||k()}),h.unqueued++,p.always(function(){p.always(function(){h.unqueued--;d.queue(a,"fx").length||h.empty.fire()})}));1===a.nodeType&&("height"in b||"width"in b)&&(c.overflow=[u.overflow,u.overflowX,u.overflowY],l=d.css(a,"display"),n="none"===l?v.get(a,"olddisplay")||Ja(a.nodeName):l,"inline"===n&&"none"===
d.css(a,"float")&&(u.display="inline-block"));c.overflow&&(u.overflow="hidden",p.always(function(){u.overflow=c.overflow[0];u.overflowX=c.overflow[1];u.overflowY=c.overflow[2]}));for(e in b)if(f=b[e],lc.exec(f)){if(delete b[e],g=g||"toggle"===f,f===(q?"hide":"show")){if("show"!==f||!w||void 0===w[e])continue;q=!0}m[e]=w&&w[e]||d.style(a,e)}else l=void 0;if(d.isEmptyObject(m))"inline"===("none"===l?Ja(a.nodeName):l)&&(u.display=l);else for(e in w?"hidden"in w&&(q=w.hidden):w=v.access(a,"fxshow",{}),
g&&(w.hidden=!q),q?d(a).show():p.done(function(){d(a).hide()}),p.done(function(){var b;v.remove(a,"fxshow");for(b in m)d.style(a,b,m[b])}),m)b=sb(q?w[e]:0,e,p),e in w||(w[e]=b.start,q&&(b.end=b.start,b.start="width"===e||"height"===e?1:0))}],prefilter:function(a,b){b?R.prefilters.unshift(a):R.prefilters.push(a)}});d.speed=function(a,b,c){var e=a&&"object"==typeof a?d.extend({},a):{complete:c||!c&&b||d.isFunction(a)&&a,duration:a,easing:c&&b||b&&!d.isFunction(b)&&b};return e.duration=d.fx.off?0:"number"==
typeof e.duration?e.duration:e.duration in d.fx.speeds?d.fx.speeds[e.duration]:d.fx.speeds._default,(null==e.queue||!0===e.queue)&&(e.queue="fx"),e.old=e.complete,e.complete=function(){d.isFunction(e.old)&&e.old.call(this);e.queue&&d.dequeue(this,e.queue)},e};d.fn.extend({fadeTo:function(a,b,c,d){return this.filter(Z).css("opacity",0).show().end().animate({opacity:b},a,c,d)},animate:function(a,b,c,e){var f=d.isEmptyObject(a),g=d.speed(b,c,e);b=function(){var b=R(this,d.extend({},a),g);(f||v.get(this,
"finish"))&&b.stop(!0)};return b.finish=b,f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,c){var e=function(a){var b=a.stop;delete a.stop;b(c)};return"string"!=typeof a&&(c=b,b=a,a=void 0),b&&!1!==a&&this.queue(a||"fx",[]),this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",h=d.timers,k=v.get(this);if(g)k[g]&&k[g].stop&&e(k[g]);else for(g in k)k[g]&&k[g].stop&&mc.test(g)&&e(k[g]);for(g=h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(c),b=!1,h.splice(g,
1));!b&&c||d.dequeue(this,a)})},finish:function(a){return!1!==a&&(a=a||"fx"),this.each(function(){var b,c=v.get(this),e=c[a+"queue"];b=c[a+"queueHooks"];var f=d.timers,g=e?e.length:0;c.finish=!0;d.queue(this,a,[]);b&&b.stop&&b.stop.call(this,!0);for(b=f.length;b--;)f[b].elem===this&&f[b].queue===a&&(f[b].anim.stop(!0),f.splice(b,1));for(b=0;g>b;b++)e[b]&&e[b].finish&&e[b].finish.call(this);delete c.finish})}});d.each(["toggle","show","hide"],function(a,b){var c=d.fn[b];d.fn[b]=function(a,d,g){return null==
a||"boolean"==typeof a?c.apply(this,arguments):this.animate(Ca(b,!0),a,d,g)}});d.each({slideDown:Ca("show"),slideUp:Ca("hide"),slideToggle:Ca("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){d.fn[a]=function(a,d,f){return this.animate(b,a,d,f)}});d.timers=[];d.fx.tick=function(){var a,b=0,c=d.timers;for(ka=d.now();b<c.length;b++)a=c[b],a()||c[b]!==a||c.splice(b--,1);c.length||d.fx.stop();ka=void 0};d.fx.timer=function(a){d.timers.push(a);a()?
d.fx.start():d.timers.pop()};d.fx.interval=13;d.fx.start=function(){Ga||(Ga=n.setInterval(d.fx.tick,d.fx.interval))};d.fx.stop=function(){n.clearInterval(Ga);Ga=null};d.fx.speeds={slow:600,fast:200,_default:400};d.fn.delay=function(a,b){return a=d.fx?d.fx.speeds[a]||a:a,b=b||"fx",this.queue(b,function(b,d){var f=n.setTimeout(b,a);d.stop=function(){n.clearTimeout(f)}})};(function(){var a=q.createElement("input"),b=q.createElement("select"),c=b.appendChild(q.createElement("option"));a.type="checkbox";
w.checkOn=""!==a.value;w.optSelected=c.selected;b.disabled=!0;w.optDisabled=!c.disabled;a=q.createElement("input");a.value="t";a.type="radio";w.radioValue="t"===a.value})();var Gb,X=d.expr.attrHandle;d.fn.extend({attr:function(a,b){return T(this,d.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){d.removeAttr(this,a)})}});d.extend({attr:function(a,b,c){var e,f,g=a.nodeType;if(3!==g&&8!==g&&2!==g)return"undefined"==typeof a.getAttribute?d.prop(a,b,c):(1===g&&d.isXMLDoc(a)||
(b=b.toLowerCase(),f=d.attrHooks[b]||(d.expr.match.bool.test(b)?Gb:void 0)),void 0!==c?null===c?void d.removeAttr(a,b):f&&"set"in f&&void 0!==(e=f.set(a,c,b))?e:(a.setAttribute(b,c+""),c):f&&"get"in f&&null!==(e=f.get(a,b))?e:(e=d.find.attr(a,b),null==e?void 0:e))},attrHooks:{type:{set:function(a,b){if(!w.radioValue&&"radio"===b&&d.nodeName(a,"input")){var c=a.value;return a.setAttribute("type",b),c&&(a.value=c),b}}}},removeAttr:function(a,b){var c,e,f=0,g=b&&b.match(P);if(g&&1===a.nodeType)for(;c=
g[f++];)e=d.propFix[c]||c,d.expr.match.bool.test(c)&&(a[e]=!1),a.removeAttribute(c)}});Gb={set:function(a,b,c){return!1===b?d.removeAttr(a,c):a.setAttribute(c,c),c}};d.each(d.expr.match.bool.source.match(/\w+/g),function(a,b){var c=X[b]||d.find.attr;X[b]=function(a,b,d){var h,k;return d||(k=X[b],X[b]=h,h=null!=c(a,b,d)?b.toLowerCase():null,X[b]=k),h}});var nc=/^(?:input|select|textarea|button)$/i,oc=/^(?:a|area)$/i;d.fn.extend({prop:function(a,b){return T(this,d.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[d.propFix[a]||
a]})}});d.extend({prop:function(a,b,c){var e,f,g=a.nodeType;if(3!==g&&8!==g&&2!==g)return 1===g&&d.isXMLDoc(a)||(b=d.propFix[b]||b,f=d.propHooks[b]),void 0!==c?f&&"set"in f&&void 0!==(e=f.set(a,c,b))?e:a[b]=c:f&&"get"in f&&null!==(e=f.get(a,b))?e:a[b]},propHooks:{tabIndex:{get:function(a){var b=d.find.attr(a,"tabindex");return b?parseInt(b,10):nc.test(a.nodeName)||oc.test(a.nodeName)&&a.href?0:-1}}},propFix:{"for":"htmlFor","class":"className"}});w.optSelected||(d.propHooks.selected={get:function(a){a=
a.parentNode;return a&&a.parentNode&&a.parentNode.selectedIndex,null}});d.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){d.propFix[this.toLowerCase()]=this});var Sa=/[\t\r\n\f]/g;d.fn.extend({addClass:function(a){var b,c,e,f,g,h,k=0;if(d.isFunction(a))return this.each(function(b){d(this).addClass(a.call(this,b,aa(this)))});if("string"==typeof a&&a)for(b=a.match(P)||[];c=this[k++];)if(f=aa(c),e=1===c.nodeType&&(" "+
f+" ").replace(Sa," ")){for(h=0;g=b[h++];)0>e.indexOf(" "+g+" ")&&(e+=g+" ");e=d.trim(e);f!==e&&c.setAttribute("class",e)}return this},removeClass:function(a){var b,c,e,f,g,h,k=0;if(d.isFunction(a))return this.each(function(b){d(this).removeClass(a.call(this,b,aa(this)))});if(!arguments.length)return this.attr("class","");if("string"==typeof a&&a)for(b=a.match(P)||[];c=this[k++];)if(f=aa(c),e=1===c.nodeType&&(" "+f+" ").replace(Sa," ")){for(h=0;g=b[h++];)for(;-1<e.indexOf(" "+g+" ");)e=e.replace(" "+
g+" "," ");e=d.trim(e);f!==e&&c.setAttribute("class",e)}return this},toggleClass:function(a,b){var c=typeof a;return"boolean"==typeof b&&"string"===c?b?this.addClass(a):this.removeClass(a):d.isFunction(a)?this.each(function(c){d(this).toggleClass(a.call(this,c,aa(this),b),b)}):this.each(function(){var b,f,g,h;if("string"===c)for(f=0,g=d(this),h=a.match(P)||[];b=h[f++];)g.hasClass(b)?g.removeClass(b):g.addClass(b);else(void 0===a||"boolean"===c)&&(b=aa(this),b&&v.set(this,"__className__",b),this.setAttribute&&
this.setAttribute("class",b||!1===a?"":v.get(this,"__className__")||""))})},hasClass:function(a){var b,c=0;for(a=" "+a+" ";b=this[c++];)if(1===b.nodeType&&-1<(" "+aa(b)+" ").replace(Sa," ").indexOf(a))return!0;return!1}});var pc=/\r/g;d.fn.extend({val:function(a){var b,c,e,f=this[0];if(arguments.length)return e=d.isFunction(a),this.each(function(c){var f;1===this.nodeType&&(f=e?a.call(this,c,d(this).val()):a,null==f?f="":"number"==typeof f?f+="":d.isArray(f)&&(f=d.map(f,function(a){return null==a?
"":a+""})),b=d.valHooks[this.type]||d.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&void 0!==b.set(this,f,"value")||(this.value=f))});if(f)return b=d.valHooks[f.type]||d.valHooks[f.nodeName.toLowerCase()],b&&"get"in b&&void 0!==(c=b.get(f,"value"))?c:(c=f.value,"string"==typeof c?c.replace(pc,""):null==c?"":c)}});d.extend({valHooks:{option:{get:function(a){return d.trim(a.value)}},select:{get:function(a){for(var b,c=a.options,e=a.selectedIndex,f="select-one"===a.type||0>e,g=f?null:[],h=f?e+
1:c.length,k=0>e?h:f?e:0;h>k;k++)if(b=c[k],!(!b.selected&&k!==e||(w.optDisabled?b.disabled:null!==b.getAttribute("disabled"))||b.parentNode.disabled&&d.nodeName(b.parentNode,"optgroup"))){if(a=d(b).val(),f)return a;g.push(a)}return g},set:function(a,b){for(var c,e,f=a.options,g=d.makeArray(b),h=f.length;h--;)e=f[h],(e.selected=-1<d.inArray(d.valHooks.option.get(e),g))&&(c=!0);return c||(a.selectedIndex=-1),g}}}});d.each(["radio","checkbox"],function(){d.valHooks[this]={set:function(a,b){return d.isArray(b)?
a.checked=-1<d.inArray(d(a).val(),b):void 0}};w.checkOn||(d.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});var Hb=/^(?:focusinfocus|focusoutblur)$/;d.extend(d.event,{trigger:function(a,b,c,e){var f,g,h,k,l,r,p,m=[c||q],u=Qa.call(a,"type")?a.type:a;f=Qa.call(a,"namespace")?a.namespace.split("."):[];if(g=h=c=c||q,3!==c.nodeType&&8!==c.nodeType&&!Hb.test(u+d.event.triggered)&&(-1<u.indexOf(".")&&(f=u.split("."),u=f.shift(),f.sort()),l=0>u.indexOf(":")&&"on"+u,a=
a[d.expando]?a:new d.Event(u,"object"==typeof a&&a),a.isTrigger=e?2:3,a.namespace=f.join("."),a.rnamespace=a.namespace?new RegExp("(^|\\.)"+f.join("\\.(?:.*\\.|)")+"(\\.|$)"):null,a.result=void 0,a.target||(a.target=c),b=null==b?[a]:d.makeArray(b,[a]),p=d.event.special[u]||{},e||!p.trigger||!1!==p.trigger.apply(c,b))){if(!e&&!p.noBubble&&!d.isWindow(c)){k=p.delegateType||u;for(Hb.test(k+u)||(g=g.parentNode);g;g=g.parentNode)m.push(g),h=g;h===(c.ownerDocument||q)&&m.push(h.defaultView||h.parentWindow||
n)}for(f=0;(g=m[f++])&&!a.isPropagationStopped();)a.type=1<f?k:p.bindType||u,(r=(v.get(g,"events")||{})[a.type]&&v.get(g,"handle"))&&r.apply(g,b),(r=l&&g[l])&&r.apply&&ra(g)&&(a.result=r.apply(g,b),!1===a.result&&a.preventDefault());return a.type=u,e||a.isDefaultPrevented()||p._default&&!1!==p._default.apply(m.pop(),b)||!ra(c)||l&&d.isFunction(c[u])&&!d.isWindow(c)&&(h=c[l],h&&(c[l]=null),d.event.triggered=u,c[u](),d.event.triggered=void 0,h&&(c[l]=h)),a.result}},simulate:function(a,b,c){a=d.extend(new d.Event,
c,{type:a,isSimulated:!0});d.event.trigger(a,null,b);a.isDefaultPrevented()&&c.preventDefault()}});d.fn.extend({trigger:function(a,b){return this.each(function(){d.event.trigger(a,b,this)})},triggerHandler:function(a,b){var c=this[0];return c?d.event.trigger(a,b,c,!0):void 0}});d.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,
b){d.fn[b]=function(a,d){return 0<arguments.length?this.on(b,null,a,d):this.trigger(b)}});d.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});w.focusin="onfocusin"in n;w.focusin||d.each({focus:"focusin",blur:"focusout"},function(a,b){var c=function(a){d.event.simulate(b,a.target,d.event.fix(a))};d.event.special[b]={setup:function(){var d=this.ownerDocument||this,f=v.access(d,b);f||d.addEventListener(a,c,!0);v.access(d,b,(f||0)+1)},teardown:function(){var d=this.ownerDocument||
this,f=v.access(d,b)-1;f?v.access(d,b,f):(d.removeEventListener(a,c,!0),v.remove(d,b))}}});var ta=n.location,Ta=d.now(),Ua=/\?/;d.parseJSON=function(a){return JSON.parse(a+"")};d.parseXML=function(a){var b;if(!a||"string"!=typeof a)return null;try{b=(new n.DOMParser).parseFromString(a,"text/xml")}catch(c){b=void 0}return(!b||b.getElementsByTagName("parsererror").length)&&d.error("Invalid XML: "+a),b};var qc=/#.*$/,Ib=/([?&])_=[^&]*/,rc=/^(.*?):[ \t]*([^\r\n]*)$/gm,sc=/^(?:GET|HEAD)$/,tc=/^\/\//,Jb=
{},Ma={},Kb="*/".concat("*"),Va=q.createElement("a");Va.href=ta.href;d.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:ta.href,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(ta.protocol),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":Kb,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/\bxml\b/,html:/\bhtml/,json:/\bjson\b/},
responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,"text html":!0,"text json":d.parseJSON,"text xml":d.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Na(Na(a,d.ajaxSettings),b):Na(d.ajaxSettings,a)},ajaxPrefilter:tb(Jb),ajaxTransport:tb(Ma),ajax:function(a,b){function c(a,b,c,h){var l,p,q,z,B=b;if(2!==L){L=2;k&&n.clearTimeout(k);e=void 0;g=h||"";t.readyState=0<a?4:0;h=200<=a&&300>a||304===a;if(c){q=m;for(var x=t,H,C,
E,I,K=q.contents,M=q.dataTypes;"*"===M[0];)M.shift(),void 0===H&&(H=q.mimeType||x.getResponseHeader("Content-Type"));if(H)for(C in K)if(K[C]&&K[C].test(H)){M.unshift(C);break}if(M[0]in c)E=M[0];else{for(C in c){if(!M[0]||q.converters[C+" "+M[0]]){E=C;break}I||(I=C)}E=E||I}q=E?(E!==M[0]&&M.unshift(E),c[E]):void 0}var A;a:{c=m;H=q;C=t;E=h;var G,J,F;q={};x=c.dataTypes.slice();if(x[1])for(G in c.converters)q[G.toLowerCase()]=c.converters[G];for(I=x.shift();I;)if(c.responseFields[I]&&(C[c.responseFields[I]]=
H),!F&&E&&c.dataFilter&&(H=c.dataFilter(H,c.dataType)),F=I,I=x.shift())if("*"===I)I=F;else if("*"!==F&&F!==I){if(G=q[F+" "+I]||q["* "+I],!G)for(A in q)if(J=A.split(" "),J[1]===I&&(G=q[F+" "+J[0]]||q["* "+J[0]])){!0===G?G=q[A]:!0!==q[A]&&(I=J[0],x.unshift(J[1]));break}if(!0!==G)if(G&&c["throws"])H=G(H);else try{H=G(H)}catch(N){A={state:"parsererror",error:G?N:"No conversion from "+F+" to "+I};break a}}A={state:"success",data:H}}q=A;h?(m.ifModified&&(z=t.getResponseHeader("Last-Modified"),z&&(d.lastModified[f]=
z),z=t.getResponseHeader("etag"),z&&(d.etag[f]=z)),204===a||"HEAD"===m.type?B="nocontent":304===a?B="notmodified":(B=q.state,l=q.data,p=q.error,h=!p)):(p=B,(a||!B)&&(B="error",0>a&&(a=0)));t.status=a;t.statusText=(b||B)+"";h?w.resolveWith(u,[l,B,t]):w.rejectWith(u,[t,B,p]);t.statusCode(D);D=void 0;r&&v.trigger(h?"ajaxSuccess":"ajaxError",[t,m,h?l:p]);y.fireWith(u,[t,B]);r&&(v.trigger("ajaxComplete",[t,m]),--d.active||d.event.trigger("ajaxStop"))}}"object"==typeof a&&(b=a,a=void 0);b=b||{};var e,f,
g,h,k,l,r,p,m=d.ajaxSetup({},b),u=m.context||m,v=m.context&&(u.nodeType||u.jquery)?d(u):d.event,w=d.Deferred(),y=d.Callbacks("once memory"),D=m.statusCode||{},B={},C={},L=0,z="canceled",t={readyState:0,getResponseHeader:function(a){var b;if(2===L){if(!h)for(h={};b=rc.exec(g);)h[b[1].toLowerCase()]=b[2];b=h[a.toLowerCase()]}return null==b?null:b},getAllResponseHeaders:function(){return 2===L?g:null},setRequestHeader:function(a,b){var c=a.toLowerCase();return L||(a=C[c]=C[c]||a,B[a]=b),this},overrideMimeType:function(a){return L||
(m.mimeType=a),this},statusCode:function(a){var b;if(a)if(2>L)for(b in a)D[b]=[D[b],a[b]];else t.always(a[t.status]);return this},abort:function(a){a=a||z;return e&&e.abort(a),c(0,a),this}};if(w.promise(t).complete=y.add,t.success=t.done,t.error=t.fail,m.url=((a||m.url||ta.href)+"").replace(qc,"").replace(tc,ta.protocol+"//"),m.type=b.method||b.type||m.method||m.type,m.dataTypes=d.trim(m.dataType||"*").toLowerCase().match(P)||[""],null==m.crossDomain){l=q.createElement("a");try{l.href=m.url,l.href=
l.href,m.crossDomain=Va.protocol+"//"+Va.host!=l.protocol+"//"+l.host}catch(W){m.crossDomain=!0}}if(m.data&&m.processData&&"string"!=typeof m.data&&(m.data=d.param(m.data,m.traditional)),ub(Jb,m,b,t),2===L)return t;(r=d.event&&m.global)&&0===d.active++&&d.event.trigger("ajaxStart");m.type=m.type.toUpperCase();m.hasContent=!sc.test(m.type);f=m.url;m.hasContent||(m.data&&(f=m.url+=(Ua.test(f)?"&":"?")+m.data,delete m.data),!1===m.cache&&(m.url=Ib.test(f)?f.replace(Ib,"$1_="+Ta++):f+(Ua.test(f)?"&":
"?")+"_="+Ta++));m.ifModified&&(d.lastModified[f]&&t.setRequestHeader("If-Modified-Since",d.lastModified[f]),d.etag[f]&&t.setRequestHeader("If-None-Match",d.etag[f]));(m.data&&m.hasContent&&!1!==m.contentType||b.contentType)&&t.setRequestHeader("Content-Type",m.contentType);t.setRequestHeader("Accept",m.dataTypes[0]&&m.accepts[m.dataTypes[0]]?m.accepts[m.dataTypes[0]]+("*"!==m.dataTypes[0]?", "+Kb+"; q=0.01":""):m.accepts["*"]);for(p in m.headers)t.setRequestHeader(p,m.headers[p]);if(m.beforeSend&&
(!1===m.beforeSend.call(u,t,m)||2===L))return t.abort();z="abort";for(p in{success:1,error:1,complete:1})t[p](m[p]);if(e=ub(Ma,m,b,t)){if(t.readyState=1,r&&v.trigger("ajaxSend",[t,m]),2===L)return t;m.async&&0<m.timeout&&(k=n.setTimeout(function(){t.abort("timeout")},m.timeout));try{L=1,e.send(B,c)}catch(W){if(!(2>L))throw W;c(-1,W)}}else c(-1,"No Transport");return t},getJSON:function(a,b,c){return d.get(a,b,c,"json")},getScript:function(a,b){return d.get(a,void 0,b,"script")}});d.each(["get","post"],
function(a,b){d[b]=function(a,e,f,g){return d.isFunction(e)&&(g=g||f,f=e,e=void 0),d.ajax(d.extend({url:a,type:b,dataType:g,data:e,success:f},d.isPlainObject(a)&&a))}});d._evalUrl=function(a){return d.ajax({url:a,type:"GET",dataType:"script",async:!1,global:!1,"throws":!0})};d.fn.extend({wrapAll:function(a){var b;return d.isFunction(a)?this.each(function(b){d(this).wrapAll(a.call(this,b))}):(this[0]&&(b=d(a,this[0].ownerDocument).eq(0).clone(!0),this[0].parentNode&&b.insertBefore(this[0]),b.map(function(){for(var a=
this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this)),this)},wrapInner:function(a){return d.isFunction(a)?this.each(function(b){d(this).wrapInner(a.call(this,b))}):this.each(function(){var b=d(this),c=b.contents();c.length?c.wrapAll(a):b.append(a)})},wrap:function(a){var b=d.isFunction(a);return this.each(function(c){d(this).wrapAll(b?a.call(this,c):a)})},unwrap:function(){return this.parent().each(function(){d.nodeName(this,"body")||d(this).replaceWith(this.childNodes)}).end()}});
d.expr.filters.hidden=function(a){return!d.expr.filters.visible(a)};d.expr.filters.visible=function(a){return 0<a.offsetWidth||0<a.offsetHeight||0<a.getClientRects().length};var uc=/%20/g,Xb=/\[\]$/,Lb=/\r?\n/g,vc=/^(?:submit|button|image|reset|file)$/i,wc=/^(?:input|select|textarea|keygen)/i;d.param=function(a,b){var c,e=[],f=function(a,b){b=d.isFunction(b)?b():null==b?"":b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};if(void 0===b&&(b=d.ajaxSettings&&d.ajaxSettings.traditional),
d.isArray(a)||a.jquery&&!d.isPlainObject(a))d.each(a,function(){f(this.name,this.value)});else for(c in a)Oa(c,a[c],b,f);return e.join("&").replace(uc,"+")};d.fn.extend({serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=d.prop(this,"elements");return a?d.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!d(this).is(":disabled")&&wc.test(this.nodeName)&&!vc.test(a)&&(this.checked||!Db.test(a))}).map(function(a,
b){var c=d(this).val();return null==c?null:d.isArray(c)?d.map(c,function(a){return{name:b.name,value:a.replace(Lb,"\r\n")}}):{name:b.name,value:c.replace(Lb,"\r\n")}}).get()}});d.ajaxSettings.xhr=function(){try{return new n.XMLHttpRequest}catch(a){}};var xc={0:200,1223:204},ga=d.ajaxSettings.xhr();w.cors=!!ga&&"withCredentials"in ga;w.ajax=ga=!!ga;d.ajaxTransport(function(a){var b,c;return w.cors||ga&&!a.crossDomain?{send:function(d,f){var g,h=a.xhr();if(h.open(a.type,a.url,a.async,a.username,a.password),
a.xhrFields)for(g in a.xhrFields)h[g]=a.xhrFields[g];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]="XMLHttpRequest");for(g in d)h.setRequestHeader(g,d[g]);b=function(a){return function(){b&&(b=c=h.onload=h.onerror=h.onabort=h.onreadystatechange=null,"abort"===a?h.abort():"error"===a?"number"!=typeof h.status?f(0,"error"):f(h.status,h.statusText):f(xc[h.status]||h.status,h.statusText,"text"!==(h.responseType||"text")||"string"!=
typeof h.responseText?{binary:h.response}:{text:h.responseText},h.getAllResponseHeaders()))}};h.onload=b();c=h.onerror=b("error");void 0!==h.onabort?h.onabort=c:h.onreadystatechange=function(){4===h.readyState&&n.setTimeout(function(){b&&c()})};b=b("abort");try{h.send(a.hasContent&&a.data||null)}catch(k){if(b)throw k;}},abort:function(){b&&b()}}:void 0});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/\b(?:java|ecma)script\b/},
converters:{"text script":function(a){return d.globalEval(a),a}}});d.ajaxPrefilter("script",function(a){void 0===a.cache&&(a.cache=!1);a.crossDomain&&(a.type="GET")});d.ajaxTransport("script",function(a){if(a.crossDomain){var b,c;return{send:function(e,f){b=d("<script>").prop({charset:a.scriptCharset,src:a.url}).on("load error",c=function(a){b.remove();c=null;a&&f("error"===a.type?404:200,a.type)});q.head.appendChild(b[0])},abort:function(){c&&c()}}}});var Mb=[],Wa=/(=)\?(?=&|$)|\?\?/;d.ajaxSetup({jsonp:"callback",
jsonpCallback:function(){var a=Mb.pop()||d.expando+"_"+Ta++;return this[a]=!0,a}});d.ajaxPrefilter("json jsonp",function(a,b,c){var e,f,g,h=!1!==a.jsonp&&(Wa.test(a.url)?"url":"string"==typeof a.data&&0===(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&Wa.test(a.data)&&"data");return h||"jsonp"===a.dataTypes[0]?(e=a.jsonpCallback=d.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,h?a[h]=a[h].replace(Wa,"$1"+e):!1!==a.jsonp&&(a.url+=(Ua.test(a.url)?"&":"?")+a.jsonp+"="+
e),a.converters["script json"]=function(){return g||d.error(e+" was not called"),g[0]},a.dataTypes[0]="json",f=n[e],n[e]=function(){g=arguments},c.always(function(){void 0===f?d(n).removeProp(e):n[e]=f;a[e]&&(a.jsonpCallback=b.jsonpCallback,Mb.push(e));g&&d.isFunction(f)&&f(g[0]);g=f=void 0}),"script"):void 0});w.createHTMLDocument=function(){var a=q.implementation.createHTMLDocument("").body;return a.innerHTML="<form></form><form></form>",2===a.childNodes.length}();d.parseHTML=function(a,b,c){if(!a||
"string"!=typeof a)return null;"boolean"==typeof b&&(c=b,b=!1);b=b||(w.createHTMLDocument?q.implementation.createHTMLDocument(""):q);var e=Ab.exec(a);c=!c&&[];return e?[b.createElement(e[1])]:(e=Za([a],b,c),c&&c.length&&d(c).remove(),d.merge([],e.childNodes))};var Nb=d.fn.load;d.fn.load=function(a,b,c){if("string"!=typeof a&&Nb)return Nb.apply(this,arguments);var e,f,g,h=this,k=a.indexOf(" ");return-1<k&&(e=d.trim(a.slice(k)),a=a.slice(0,k)),d.isFunction(b)?(c=b,b=void 0):b&&"object"==typeof b&&(f=
"POST"),0<h.length&&d.ajax({url:a,type:f||"GET",dataType:"html",data:b}).done(function(a){g=arguments;h.html(e?d("<div>").append(d.parseHTML(a)).find(e):a)}).always(c&&function(a,b){h.each(function(){c.apply(h,g||[a.responseText,b,a])})}),this};d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){d.fn[b]=function(a){return this.on(b,a)}});d.expr.filters.animated=function(a){return d.grep(d.timers,function(b){return a===b.elem}).length};d.offset={setOffset:function(a,
b,c){var e,f,g,h,k,l,n=d.css(a,"position"),p=d(a),m={};"static"===n&&(a.style.position="relative");k=p.offset();g=d.css(a,"top");l=d.css(a,"left");("absolute"===n||"fixed"===n)&&-1<(g+l).indexOf("auto")?(e=p.position(),h=e.top,f=e.left):(h=parseFloat(g)||0,f=parseFloat(l)||0);d.isFunction(b)&&(b=b.call(a,c,d.extend({},k)));null!=b.top&&(m.top=b.top-k.top+h);null!=b.left&&(m.left=b.left-k.left+f);"using"in b?b.using.call(a,m):p.css(m)}};d.fn.extend({offset:function(a){if(arguments.length)return void 0===
a?this:this.each(function(b){d.offset.setOffset(this,a,b)});var b,c,e=this[0],f={top:0,left:0},g=e&&e.ownerDocument;if(g)return b=g.documentElement,d.contains(b,e)?(f=e.getBoundingClientRect(),c=vb(g),{top:f.top+c.pageYOffset-b.clientTop,left:f.left+c.pageXOffset-b.clientLeft}):f},position:function(){if(this[0]){var a,b,c=this[0],e={top:0,left:0};return"fixed"===d.css(c,"position")?b=c.getBoundingClientRect():(a=this.offsetParent(),b=this.offset(),d.nodeName(a[0],"html")||(e=a.offset()),e.top+=d.css(a[0],
"borderTopWidth",!0),e.left+=d.css(a[0],"borderLeftWidth",!0)),{top:b.top-e.top-d.css(c,"marginTop",!0),left:b.left-e.left-d.css(c,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent;a&&"static"===d.css(a,"position");)a=a.offsetParent;return a||sa})}});d.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c="pageYOffset"===b;d.fn[a]=function(d){return T(this,function(a,d,e){var k=vb(a);return void 0===e?k?k[b]:a[d]:void(k?k.scrollTo(c?
k.pageXOffset:e,c?e:k.pageYOffset):a[d]=e)},a,d,arguments.length)}});d.each(["top","left"],function(a,b){d.cssHooks[b]=La(w.pixelPosition,function(a,e){return e?(e=ja(a,b),Ka.test(e)?d(a).position()[b]+"px":e):void 0})});d.each({Height:"height",Width:"width"},function(a,b){d.each({padding:"inner"+a,content:b,"":"outer"+a},function(c,e){d.fn[e]=function(e,g){var h=arguments.length&&(c||"boolean"!=typeof e),k=c||(!0===e||!0===g?"margin":"border");return T(this,function(b,c,e){var f;return d.isWindow(b)?
b.document.documentElement["client"+a]:9===b.nodeType?(f=b.documentElement,Math.max(b.body["scroll"+a],f["scroll"+a],b.body["offset"+a],f["offset"+a],f["client"+a])):void 0===e?d.css(b,c,k):d.style(b,c,e,k)},b,h?e:void 0,h,null)}})});d.fn.extend({bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,d){return this.on(b,a,c,d)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)},size:function(){return this.length}});
d.fn.andSelf=d.fn.addBack;"function"==typeof define&&define.amd&&define("jquery",[],function(){return d});var yc=n.jQuery,zc=n.$;return d.noConflict=function(a){return n.$===d&&(n.$=zc),a&&n.jQuery===d&&(n.jQuery=yc),d},y||(n.jQuery=n.$=d),d});window.Castacencio=window.Castacencio||{};Castacencio.View=Castacencio.View||{};
Castacencio.View.preload=function(){function n(n){ha.text(parseInt(n))}function y(){var y=0;B.length&&(y=parseInt(Y/B.length*100));qa.stop().animate({width:y+"%"},1E3);O.stop().animate({percentage:y},{duration:1E3,step:n})}function K(){qa.stop().animate({width:"100%"},500);O.stop().animate({percentage:100},{duration:500,step:n}).css({opacity:1}).animate({opacity:0},function(){O.css({display:"none"});$("#site").css({opacity:1})});Backbone.history.start()}var B=$("body").find("img[src]");$("body [style]").each(function(){var n=
$(this).css("background-image").replace(/^url\(["']?/,"").replace(/["']?\)$/,"");n&&"none"!=n&&(B=B.add($('<img src="'+n+'"/>')))});var O=$("#loader-container"),qa=$("#loader-percentage-line"),ha=$("#loader-percentage"),Y=0;B.length&&(y(),B.load(function(){$(this).off("load");Y++;y()}));$(window).load(function(){K()})};$(function(){Castacencio.View.preload()});
